### ISSUE TITLE
community.docker.docker_image_build: changes in platform are not considered

### ISSUE THREAD

**Issue by toralf** [ansible-collections/community.docker#1000]
If I change 
```
platform: '{{ docker_fps_open_liberty_platforms }}'
```
from 
```
docker_fps_open_liberty_platforms: ['linux/amd64']
```
to
```
docker_fps_open_liberty_platforms: ['linux/amd64', 'linux/arm64']
```
then the ARM platform is not "added" when I re-run the playbook.

What helps however is
```
docker system prune -a
```
at the command line.
(hardened stable Gentoo Linux).

**Comment by felixfontein** [comment]
Please read the documentation, in particular the second paragraph of Synopsis: https://docs.ansible.com/ansible/devel/collections/community/docker/docker_image_build_module.html#synopsis

**Comment by toralf** [comment]
ah -ok, thx
