### ISSUE TITLE
Support docker-compose profiles

### ISSUE THREAD

**Issue by Its-Alex** [ansible-collections/community.docker#116]
##### SUMMARY

Hi, I would like to know if there is a possibility to support the [`profiles`](https://docs.docker.com/compose/profiles/) features from docker-compose?

Or maybe there is already some way to use this feature?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker-compose

**Comment by felixfontein** [comment]
I don't think the module (https://github.com/ansible-collections/community.docker/blob/main/plugins/modules/docker_compose.py) allows to use that right now. It shouldn't be that hard to implement though. If you're interested, feel free to create a PR!

**Comment by hummeltech** [comment]
It looks like this feature have been implemented, should this be closed?

**Comment by felixfontein** [comment]
Looks like it has been! Thanks for noticing, I will close this.
