### ISSUE TITLE
docker_plugin add the ability to specify install options

### ISSUE THREAD

**Issue by northshade** [ansible-collections/community.docker#145]
##### SUMMARY
Add the ability to specify install options as in the example below.

<code>docker plugin install --alias glusterfs --grant-all-permissions mochoa/glusterfs-volume-plugin SERVER=server01</code>

<pre>
<code>
- name: Install a plugin with install options as well as plugin options
  community.docker.docker_plugin:
        plugin_name: mochoa/glusterfs-volume-plugin
        install_options:
            alias: glusterfs
            grant_all_permissions: true
        plugin_options:
            SERVER: "server01"
</code>
</pre>
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.docker.docker_plugin

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by Ajpantuso** [comment]
`--alias` can definitely be made an option, but by nature of the API `--grant-all-permissions` and `--disabled` are true by default. `state=enable` vs `state=present` for an uninstalled plugin already handles the `--disabled` behavior, but for `--grant-all-permissions` the user would have to know each individual permissions beforehand (or we'd need an info module).

**Comment by felixfontein** [comment]
Part of this has already been implemented in #161, and the remainder seems to be problematic to implement.
