### ISSUE TITLE
Inventory plugin should propagate docker_host variable

### ISSUE THREAD

**Issue by ytimenkov** [ansible-collections/community.docker#155]
##### SUMMARY
I use inventory plugin with remote docker_host. However it is not propagated to the connection plugin and the latter uses default local connection.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.docker.docker_containers

##### ANSIBLE VERSION
```paste below
ansible 2.10.5
  config file = /home/default/dev-container/ansible.cfg
  configured module search path = ['/home/default/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.4 (default, Apr  4 2021, 19:38:44) [GCC 10.2.1 20210401]
```

##### CONFIGURATION
```paste below
DEFAULT_HOST_LIST(/home/default/dev-container/ansible.cfg) = ['/home/default/dev-container/inventory']
```

##### OS / ENVIRONMENT
Ubuntu 21.04

##### STEPS TO REPRODUCE
Inventory:
```yaml
plugin: community.docker.docker_containers
docker_host: tcp://my-host:2376
```

##### EXPECTED RESULTS
I can use those hosts in my playbook, they should connect to `my-host:2376` 

##### ACTUAL RESULTS
Playbook fails with:
```
TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************************
fatal: [dev-vm]: UNREACHABLE! => {"changed": false, "msg": "Could not find container \"dev-vm\" (404 Client Error for http+docker://localhost/v1.40/containers/dev-vm/exec: Not Found (\"No such container: dev-vm\"))", "unreachable": true}
```

However ansible-inventory successfully finds containers:

```
$ ansible-inventory --graph --vars
@all:
  |--@ungrouped:
  |  |--dev-vm
  |  |  |--{ansible_connection = community.docker.docker_api}
  |  |  |--{ansible_host = dev-vm}
  |  |  |--{docker_name = dev-vm}
  |  |  |--{docker_short_id = e1a86cd6a5599}
```

##### Workaround

To work around I added variable explicitly to inventory:
```yaml
plugin: community.docker.docker_containers
docker_host: tcp://my-host:2376
compose:
  ansible_docker_docker_host: "'tcp://my-host:2376'"
```
But this looks like a hack and unnecessary duplication.

**Comment by felixfontein** [comment]
Thanks for the report! This definitely makes sense. I guess this would also apply to other configs that are needed to connect to the Docker daemon (like TLS setup).

**Comment by felixfontein** [comment]
I've implemented this in #157. Can you please try it out whether it works for you?

**Comment by ytimenkov** [comment]
Dumb question: how can I install it? I tried the most obvious `ansible-galaxy collection install https://github.com/felixfontein/community.docker/archive/refs/heads/pass-docker-params.tar.gz` hoping it will pull your development branch, but it `ansible-galaxy` says: "Collection does not contain the required file MANIFEST.json.".

**Comment by felixfontein** [comment]
Here are some instructions on how you can try it locally: https://github.com/ansible/community-docs/blob/main/test_pr_locally_guide.rst

**Comment by ytimenkov** [comment]
It worked. Thanks! `ansible_docker_docker_host` doesn't show up in the `ansible-inventory` output but I could run playbook inside remote container.

**Comment by ytimenkov** [comment]
In my deleted comment I found that ansible didn't pick up the cloned repo and ran my local docker 😊

The instructions didn't work: it refused to parse inventory (for some reason), although showed that there are 2 `community.docker` collections are available. I tried `ansible-galaxy collection build` and then installed tarball.

After that I see variables added into inventory and I've ran playbook. (Had local docker turned off completely this time).

**Comment by felixfontein** [comment]
Thanks for testing the PR!

> The instructions didn't work: it refused to parse inventory (for some reason), although showed that there are 2 `community.docker` collections are available. I tried `ansible-galaxy collection build` and then installed tarball.

Hmm, it would be interesting to know why it didn't work, so we can improve the instructions.

I guess "showed that there are 2 community.collections" means that you looked at the `ansible-galaxy collection list` output? That's to be expected; ansible-core uses the first one it finds, but `collection list` also shows other instances of the collection found in the collection search path.
