### ISSUE TITLE
True/False cannot be used as env value through an Ansible variable

### ISSUE THREAD

**Issue by calvinbui** [ansible-collections/community.docker#156]
##### SUMMARY

Using an environment variable value of `True` or `False` in an Ansible variable leads to the error:

```
Non-string value found for env option. Ambiguous env options must be wrapped in quotes to avoid them being interpreted
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- community.docker.docker_container

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.1] 
  config file = /home/calvin/ansible-monorepo/ansible.cfg
  configured module search path = ['/home/calvin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/calvin/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/calvin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/calvin/.local/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

Also tested devel with the same result:
```
ansible [core 2.12.0.dev0]
  config file = /home/calvin/ansible-monorepo/ansible.cfg
  configured module search path = ['/home/calvin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/calvin/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/calvin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/calvin/.local/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/calvin/ansible-monorepo/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/calvin/ansible-monorepo/ansible.cfg) = True
DEFAULT_BECOME(/home/calvin/ansible-monorepo/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/calvin/ansible-monorepo/ansible.cfg) = ['/home/calvin/ansible-monorepo/inventory.yml']
DEFAULT_VAULT_PASSWORD_FILE(/home/calvin/ansible-monorepo/ansible.cfg) = /home/calvin/.vault_pass.txt
```

##### OS / ENVIRONMENT

Windows 10 with WSL2 (Ubuntu 20.04)

##### STEPS TO REPRODUCE

```yaml
vars:
  enable_debug: "True"

tasks:
- name: Create my container
  community.docker.docker_container:
  ...
    env:
      DEBUG: "{{ enable_debug }}"
```

Other tests and results with the above example:

| usage                                      | result   |
|--------------------------------  |---------| 
| `DEBUG: "True"`                       | ✔️ |
| `DEBUG: "{{ 'True' }}"`               | ❌ |
| `DEBUG: "{{ 'true' }}"`               | ✔️ |
| `DEBUG: "{{ 'True' \| quote }}"` | ❌ |
| `DEBUG: "{{ 'true' \| quote }}"` | ✔️  |
| `DEBUG: "{{ 'TRUE' \| capitalize \| quote \| splitext \| join('') }}"` |  ❌ |

##### EXPECTED RESULTS

The boolean to be parsed as a String

##### ACTUAL RESULTS

The error `"msg": "Non-string value found for env option. Ambiguous env options must be wrapped in quotes to avoid them being interpreted. ` is thrown

**Comment by felixfontein** [comment]
This is pretty much unrelated to the docker_container module, but more an Ansible support question: how to avoid Ansible mangling strings that look like booleans or other values? (Which is unfortunately something that happens a lot if your strings look like integers, floats, booleans, Python dics, ...) The answer is to use the `string` filter:
```.yaml
vars:
  enable_debug: "True"

tasks:
- name: Create my container
  community.docker.docker_container:
    ...
    env:
      DEBUG: "{{ enable_debug | string }}"
```

**Comment by calvinbui** [comment]
The `string` filter works. I was wondering where I could find docs for that but it's probably documented over in Jinja. Thanks!

**Comment by felixfontein** [comment]
It's probably not documented in Jinja since it's more an Ansible problem. Ansible does a lot of 'magic' that has a lot of unintended side-effects, like this one. Unfortunately it is basically impossible to fix this since fixing it would break a huge amount of other things (and existing roles/playbooks that worked fine so far). I've also tried to search for a place where this is documented, but couldn't really find something. I think it has been mentioned a lot on the ansible-project mailing list though. I also hoped that https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-jinja2-native might help here (and tried it first), but that didn't help in this specific case...

**Comment by felixfontein** [comment]
resolved_by_pr #158
