### ISSUE TITLE
docker_image: support multi tag

### ISSUE THREAD

**Issue by thaygiaoth** [ansible-collections/community.docker#165]
Currently there is

tag: "tag_number" 

Please support multi tag such as:

tag:
   - "1.1"
   - "lastest"

equivalent to:

$ docker build -t name1:tag1 -t name1:tag2

Thank you

**Comment by felixfontein** [comment]
Right now, you can simply run the `docker_image` module in a loop to add as many tags as you want to the built image.

**Comment by thaygiaoth** [comment]
Also, there is another case

- name: Add multi tags for docker image
  community.docker.docker_image:
    name: myimage:v2                                         --> tag here v2 will be overwrite v1 of tag below
    tag: v1

--> in the case multi tags --> includes name: myimage:v2 +  multi tags of tag

By the way

Please update document link with example about **docker_image multi tags**

https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html

Thank you very much!

**Comment by felixfontein** [comment]
The examples already show how to tag an image with another tag:
```.yaml
- name: Add tag latest to image
  community.docker.docker_image:
    name: myimage:7.1.2
    repository: myimage:latest
    # As 'latest' usually already is present, we need to enable overwriting of existing tags:
    force_tag: yes
    source: local
```
This will tag `myimage:7.1.2` also as `latest`.

By using the standard Ansible construct `loop` you can run that task multiple times with other tasks. I don't really think there needs to be a separate example for that. It will simply be:
```.yaml
- name: Add tags "latest" and "another_tag" to image
  community.docker.docker_image:
    name: myimage:7.1.2
    repository: "myimage:{{ item }}"
    force_tag: yes
    source: local
  loop:
    - latest
    - another_tag
```
If someone desperately cannot find the solution, searching the net should provide them with this issue, where they can now find an example.
