### ISSUE TITLE
docker_compose - misleading import error when `six` is not installed

### ISSUE THREAD

**Issue by briantist** [ansible-collections/community.docker#171]
##### SUMMARY

When `docker` and `docker-compose` pip packages are installed, but `six` is not, the error message suggests that one of the former two are missing. The end of the message shows the real issue, but this is easy to miss.

> Failed to import the required Python library (Docker SDK for Python: docker above 5.0.0 (Python >= 3.6) or docker before 5.0.0 (Python 2.7) or docker-py (Python 2.6)) on fv-az252-19's Python /opt/hostedtoolcache/Python/3.8.10/x64/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` (Python >= 3.6) or `pip install docker==4.4.4` (Python 2.7) or `pip install docker-py` (Python 2.6). The error was: No module named 'six'

It's pretty minor, but it did throw me off a bit. 

Here's a GHA output that shows this in action: https://github.com/briantist/community.hashi_vault/runs/2966310215?check_suite_focus=true#step:11:235

Note that this is an experimental thing I was trying so you won't see it elsewhere.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_compose

##### ANSIBLE VERSION

stable-2.11 & python 3.6 (I think it happened on all combinations in the matrix)

##### COLLECTION VERSION

1.8.0

##### OS / ENVIRONMENT

ubuntu 20.04 (GHA)

##### EXPECTED RESULTS

The `six` dependency is called out more prominently.

##### ACTUAL RESULTS

The message strongly suggests the issue is that `docker` or `docker-compose` are missing or are the wrong versions.

**Comment by felixfontein** [comment]
Well, this is a problem with docker, see also https://github.com/docker/docker-py/issues/2842 or https://github.com/ansible-collections/community.docker/issues/57#issuecomment-848580351

There is a PR at Docker SDK for Python to fix this (https://github.com/docker/docker-py/pull/2844) but it hasn't really progressed...

**Comment by briantist** [comment]
I see, I assumed it was upstream (thought does look pretty egregious, looks like the PR is stuck on the fact that they can't get a test environment that doesn't already have `six`). I may have mistakenly assumed that the detailed error message shown is coming from this collection and could be improved, but I see the difficulty.

Anyway as I said, it's quite minor, if you think it's not worth the effort (since it'll get fixed eventually) I'd understand if you want to close it. Or leave it open as a signpost with the intended resolution being to wait on the upstream fix. Thanks!

**Comment by felixfontein** [comment]
The message comes from this collection, but I'm not sure it's worth to improve the error message for this specific bug of Docker SDK for Python. In any case, I woud have assumed that the maintainers of Docker SDK for Python would make sure this is fixed and a release without this bug released pretty quickly...

**Comment by briantist** [comment]
> I would have assumed that the maintainers of Docker SDK for Python would make sure this is fixed and a release without this bug released pretty quickly...

I would think so too... while it makes sense to want to remove the remaining `six` imports, with it taking over a month to complete you'd thinks omeone would just.. add it back to the dependencies as the quickest "fix", and then that dep can be removed in the same PR where the imports are deleted. 😞

**Comment by felixfontein** [comment]
It has been fixed (https://github.com/docker/docker-py/pull/2863), but there's still no new release, so the fix doesn't help...

**Comment by felixfontein** [comment]
Docker SDK for Python 5.0.1/5.0.2 have been released, both should fix this issue.

**Comment by felixfontein** [comment]
Closing since this should no longer be an issue with the latest Docker SDK for Python.
