### ISSUE TITLE
Support "docker-compose pull" only 

### ISSUE THREAD

**Issue by trygvis** [ansible-collections/community.docker#184]
##### SUMMARY
Support "pull only" for docker compose. I want to pre-fetch the images before starting the services.

In my case the `docker-compose up` is done through systemd. On new hosts the service startup takes too long because pulling all the images can be slow, resulting in systemd killing and restarting the service.

AFAIKT I can't use `state: present` or `state: absent` because that will start/stop the services too. I just want to pull the images.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker compose

**Comment by felixfontein** [comment]
The community.docker.docker_compose module has been removed from today's 4.0.0 release. If you are still using it, please upgrade to community.docker.docker_compose_v2, which no longer uses the End of Life versions Docker Compose 1.x.y, but Docker's Compose plugin (version 2.x.y range).

For community.docker.docker_compose_v2, you can use community.docker.docker_compose_v2_pull.
