### ISSUE TITLE
docker_swarm_service: add support for sysctl parameter

### ISSUE THREAD

**Issue by lem8r** [ansible-collections/community.docker#190]
##### SUMMARY
Since Docker API 1.40 there is sysctl parameter for swarm services.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker_swarm_service

##### ADDITIONAL INFORMATION
In some cases there is a need to configure service's sysctl parameters. In my case it is `net.ipv4.tcp_keepalive_*` for database service. To prevent closing TCP socket on long running requests.

It looks like so when starting from command line
```bash
docker service create \
my_service \
--sysctl net.ipv4.tcp_keepalive_time=600 \
--sysctl net.ipv4.tcp_keepalive_intvl=60 \
--sysctl net.ipv4.tcp_keepalive_probes=6 \
image:1.0
```

**Comment by WojciechowskiPiotr** [comment]
I think it is a good feature proposal. Will implement it in September.

**Comment by Ranger-X** [comment]
September is over :-) 
Is there any news on this feature request?

**Comment by lem8r** [comment]
Year of September was not specified 🤷‍♂️

**Comment by WojciechowskiPiotr** [comment]
After further investigation, I found that `sysctl` is not implemented in https://github.com/docker/docker-py yet. This needs to be added there first so we can use it in the Ansible module.

I opened a request for this feature https://github.com/docker/docker-py/issues/2907

**Comment by NairolfL** [comment]
#836 was merged, I think this can be closed :)

**Comment by lem8r** [comment]
@NairolfL Thank you!
