### ISSUE TITLE
Allow to chdir for the modules where it's missing and it would make sense

### ISSUE THREAD

**Issue by Porkepix** [ansible-collections/community.docker#199]
##### SUMMARY
Some modules such as https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#ansible-collections-community-docker-docker-container-module already allows for a `chdir`while some others like https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html#ansible-collections-community-docker-docker-compose-module doesn't. It would make sense to add it to that module, and probably others if it's missing elsewhere.

##### ISSUE TYPE
- Feature Idea

**Comment by felixfontein** [comment]
I'm not sure what a `chdir` option should do for the docker_compose module. For docker_compose and docker_stack, the working directory is part of the compose definition (see https://github.com/compose-spec/compose-spec/blob/master/spec.md#working_dir). For docker_container, docker_container_exec, and docker_swarm_service, the options are already there (it's called `working_dir` for the latter).

**Comment by Porkepix** [comment]
Well, this would come handy when to it comes to the use of the `files:` option so that when listing files there's no need to repeat an absolute path for every entry in the list. It could be named prefix if you'd rather, but having some consistency and offer `chdir` in more modules didn't seem especially strange to me, but maybe did I take the issue by a wrong end?

**Comment by felixfontein** [comment]
`chdir` is about the working directory *in the container*, not about where the module is run.

**Comment by Porkepix** [comment]
> `chdir` is about the working directory _in the container_, not about where the module is run.

Okay, my bad then, I guess I was confused by the fact it's used differently for the `command` module and that's what we had. Then I guess the term is not the correct one, but you got my point about where to find those files to avoid repeating the directory with an absolute path, I guess?

Do you think that's something that might be worth thinking about? (And in such case I guess issue's title isn't really a correct one anymore).

**Comment by felixfontein** [comment]
> Okay, my bad then, I guess I was confused by the fact it's used differently for the `command` module and that's what we had. Then I guess the term is not the correct one, but you got my point about where to find those files to avoid repeating the directory with an absolute path, I guess?

I understand what you mean. I'm not aware of a general mechanism for that. Usually people use Jinja2 expressions for this. (The `path_join` filter might be useful for that; see https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#managing-file-names-and-path-names for that one and some more path related filters.)

> Do you think that's something that might be worth thinking about? (And in such case I guess issue's title isn't really a correct one anymore).

I don't think it makes sense to look at this for docker modules. If this is solved, there should better be a mechanism which works in all of Ansible. I've never had the need for something like this though, and it's the first time I see someone asking for it, so I'm not sure whether it's worth adding something for that.

**Comment by Porkepix** [comment]
> > Okay, my bad then, I guess I was confused by the fact it's used differently for the `command` module and that's what we had. Then I guess the term is not the correct one, but you got my point about where to find those files to avoid repeating the directory with an absolute path, I guess?
> 
> I understand what you mean. I'm not aware of a general mechanism for that. Usually people use Jinja2 expressions for this. (The `path_join` filter might be useful for that; see [docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#managing-file-names-and-path-names](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#managing-file-names-and-path-names) for that one and some more path related filters.)

This doesn't seems like a way to not repeat the path or a pattern for every list entry, or I might not be understand this correctly?

**Comment by felixfontein** [comment]
With some Jinja2 trickery you could do something like:
```
- hosts: localhost
  tasks:
    - debug:
        msg: "{{ names | zip_longest([], fillvalue=base) | map('reverse') | map('path_join') }}"
      vars:
        names:
          - a
          - b
          - c
        base: /f/g/h
```
This gives
```
TASK [debug] *************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "/f/g/h/a",
        "/f/g/h/b",
        "/f/g/h/c"
    ]
}
```

**Comment by felixfontein** [comment]
Closing since this isn't something this collection will implement.
