### ISSUE TITLE
Support for Compose v3?

### ISSUE THREAD

**Issue by tstackhouse** [ansible-collections/community.docker#206]
Compose v3 has been available since January 2017, over 4.5 years ago, yet only v2 and the deprecated v1 formats are listed as supported.  This makes migrating existing v3 compose based services much more complicated than it needs to or should be.  Is there a timeline for adding v3 compose support? Is it a documentation issue?

**Comment by felixfontein** [comment]
Have you tried using the module with verison 3?

**Comment by Ajpantuso** [comment]
I tested out our integration tests with v3 and encountered no issues. Local tests with v3 specific features also seemed okay. Given a sufficient `docker` and `docker-compose` version there should not be issues with v3, but I would be cautious of using the `definition` with relative paths for some of the v3 specific keywords such as `build` or `build.context`.

**Comment by felixfontein** [comment]
Thanks for testing this! I guess the documentation needs to be fixed; maybe it's best to avoid to explicitly mention supported versions?

> I would be cautious of using the `definition` with relative paths for some of the v3 specific keywords such as `build` or `build.context`.

I would always avoid relative paths, **except** if you explicitly work on localhost. Otherwise relative paths are usually a path to disaster :)

**Comment by felixfontein** [comment]
(Or add something like "Newer versions probably work as well, but haven't been tested yet.")
