### ISSUE TITLE
Add 'platform' option to build options in docker_image

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.docker#22]
##### SUMMARY

I need to support multi-arch builds for some of my Docker images (e.g. support amd64 and arm64), and doing so requires running `docker build` with the `--platform` argument. It seems the `docker_image` module doesn't support that argument right now, so if I want to do this I have to use `command`:

```yaml
- command: docker build --platform arm64 --pull -t geerlingguy/my-image:latest-arm64 .
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_image

##### ADDITIONAL INFORMATION
Related issue: https://github.com/geerlingguy/drupal-container/issues/24

**Comment by felixfontein** [comment]
resolved_by_pr #54
