### ISSUE TITLE
Simple restart of a container 

### ISSUE THREAD

**Issue by thomasthe1st** [ansible-collections/community.docker#229]
##### SUMMARY
Ideally speaking there should be command to just restart a docker container in an easy way.
It seems the restart flag on the docker_container module does not just restart the container.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker_container maybe would be better to put it somewhere else

##### ADDITIONAL INFORMATION
I have a docker container which initially was run with following command:
`docker run -d -p 12101:12101  --name rhasspy --restart unless-stopped  -v "$HOME/.config/rhasspy/profiles:/profiles"  -v "/etc/localtime:/etc/localtime:ro"  --device /dev/snd:/dev/snd  rhasspy/rhasspy  --user-profiles /profiles  --profile de --certfile /path/to/fullchain.pem --keyfile /path/to/keyfile.pem`
I tried restarting this docker container and I understood from how ansible and docker_container are being used that I need to specify all the parameters. So I ended up with this:
`
    - name: Restart rhasspy container

      community.docker.docker_container:
        name: rhasspy
        image: rhasspy/rhasspy
        state: started
        restart: yes
        restart_policy: unless-stopped
        default_host_ip: ""
        ports:
          - "12101:12101"
        volumes:
          - /home/pi/.config/rhasspy/profiles:/profiles
          - /etc/localtime:/etc/localtime:ro
        devices:
          - /dev/snd:/dev/snd
        command: --user-profiles /profiles  --profile de --certfile /profiles/fullchain.pem --keyfile /profiles/privkey.pem
      when: inventory_hostname in groups['rhasspys']
`

However it did not simply restart the container it somehow seems to rebuild the container at least from what I can tell.
In case I restart it with `docker restart rhasspy` or `docker stop rhasspy; docker start rhasspy` everything is fine. 
In case I use above mentioned ansible module I notice that I need to rehash all certificates under /etc/ssl/certs. While this is of course an issue in the image (at least as far as I can see it) it usually only happens if I run the container from image for the first time. Here however it happens on every restart. 
So I don't know if I do something wrong here or my understanding is wrong but for now I have fallen back to use ansible command module with just handing over `docker restart rhasspy` and that seems to work fine. 
Anything obvious I'm missing?
Sorry if this is not the correct place but I have not found a forum to first ask a question on this.

**Comment by felixfontein** [comment]
Have you tried passing `--diff -C` to ansible-playbook to run this in check mode and see what the module tries to change? it will show you why exactly it re-creates the container (very likely because another option you passed does not match one of the values the container currently has).

The best way is probably to specify the bare minimum of parameters possible to docker_container, and to `comparisons` with `*: ignore`, like this:
```.yaml
  community.docker.docker_container:
    name: rhasspy
    image: rhasspy/rhasspy
    state: started
    restart: yes
    comparisons:
      '*': ignore
```
This disables all idempotency checks for re-creation and container updating.

**Comment by felixfontein** [comment]
@thomasthe1st ping

**Comment by felixfontein** [comment]
Closing since this should already work fine.
