### ISSUE TITLE
docker_compose: fails with details even when debug is true

### ISSUE THREAD

**Issue by ssbarnea** [ansible-collections/community.docker#23]
##### SUMMARY
docker_compose: fails with details even when debug is true, making impossible to identify the failure reason.

The only workaround is to produce a real `docker-compose.yml` and directly call docker-compose in order to see what was the error.

I mention that even the docker daemon logs are not using in this case.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_compose

##### ANSIBLE VERSION

```paste below
2.9.9
```

##### STEPS TO REPRODUCE

```yaml
          docker_compose:
            debug: true  # <-- has no effect whatsoever!
```

##### EXPECTED RESULTS
See the real error, similar to the output of `docker-compose` cli, which in my case produced something like:
```
Creating unifi ... error

ERROR: for unifi  Cannot create container for service unifi: Conflict. The container name "/unifi" is already in use by container "3832eace0d077c259cc34a85d4140fe6b998dbd9790690e5eebf53d7854863cf". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for unifi  Cannot create container for service unifi: Conflict. The container name "/unifi" is already in use by container "3832eace0d077c259cc34a85d4140fe6b998dbd9790690e5eebf53d7854863cf". You have to remove (or rename) that container to be able to reuse that name.
Encountered errors while bringing up the project.
```

##### ACTUAL RESULTS
```paste below
    "msg": "Error starting project Encountered errors while bringing up the project."
```

**Comment by josemaia** [comment]
Is there a workaround to easily output the docker-compose.yml that ansible generates? It's a frustrating experience to be forced to build one manually to debug this.

**Comment by felixfontein** [comment]
@josemaia the module either uses the provided docker-compose.yml file, or writes the contents of `definition:` into a docker-compose.yml file without any modification (only encoding as YAML). Since you are providing these contents, you can do with that data whatever you want.

If you have
```.yaml
- docker_compose:
    definition: "{{ xxxxx }}"
```
you can simply create a task
```.yaml
- copy:
    dest: /path/to/docker-compose.yml
    content: "{{ xxxxx | to_nice_yaml }}"
```
to write the contents of `xxxxx` into a file.

**Comment by felixfontein** [comment]
We already extended the failure output of docker_compose a longer time ago, so I *think* this is no longer necessary. If it still is, please create a new issue with a new example with the latest code. Thanks.
