### ISSUE TITLE
[Feature Request] docker-compose config -q

### ISSUE THREAD

**Issue by lonix1** [ansible-collections/community.docker#24]
I was told to move this here, from https://github.com/ansible/ansible/issues/62745

---

A `docker-compose` file (and a corresponding `.env` file), can be validated for correctness like this:

````
docker-compose config -q
````

Please add that capability to the [docker_compose](https://docs.ansible.com/ansible/latest/modules/docker_compose_module.html) module.

Many modules have a `validate` argument, perhaps the same can be done here?

**Comment by felixfontein** [comment]
The community.docker.docker_compose module has been removed from today's 4.0.0 release. If you are still using it, please upgrade to community.docker.docker_compose_v2, which no longer uses the End of Life versions Docker Compose 1.x.y, but Docker's Compose plugin (version 2.x.y range).
