### ISSUE TITLE
Cannot use docker_compose in 2.1.0

### ISSUE THREAD

**Issue by EricAtORS** [ansible-collections/community.docker#267]
##### SUMMARY
docker_compose fails in 2.1.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
```
- name: start registry
  community.docker.docker_compose:
    project_src: "{{ docker_compose_storage_path }}/registry/"
```
##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/eric/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

##### COLLECTION VERSION

```
$ ansible-galaxy collection list community.docker
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
```

##### CONFIGURATION

```
# no output
```

##### OS / ENVIRONMENT

Ubuntu 20.04 on WSL. Pretty much vanilla

##### STEPS TO REPRODUCE

Run `ansible-galaxy collection install community.docker:2.1.0`

```
- name: start registry
  community.docker.docker_compose:
    project_src: "/docker/registry/"

```

Right now, down grading to community.docker == 2.0.2 works.

##### EXPECTED RESULTS

For it to start my docker-compose stack.

##### ACTUAL RESULTS

```
TASK [docker-registry : start registry] ********************************************************************************fatal: [internal]: FAILED! => {"msg": "Could not find imported module support code for version.  Looked for either LooseVersion.py or version.py"}      
```

**Comment by felixfontein** [comment]
Please note that Ansible 2.9.6 is really old and has a lot of security issues and bugs that have been fixed in later 2.9.x releases.

In any case, this seems to be a problem with Ansible 2.9.x that was fixed in Ansible 2.9.20; 2.9.19 still produces the same error message.

**Comment by felixfontein** [comment]
This is probably related to https://github.com/ansible/ansible/commit/f8caa43dc7a7beaf66e719e1e5f7bc6ff70fa7e6 (2.9.20); it was also backported to ansible-base 2.10 in https://github.com/ansible/ansible/commit/51852557dffc2ce5f501c1ab4986e867f55fec07, which appeared in ansible-base 2.10.8.

**Comment by EricAtORS** [comment]
@felixfontein 
Thanks for pointing it out.
2.9.6 is the default version inside of the ubuntu 20.04 repositories.

I'll look in to how I can upgrade it to a more recent version.

**Comment by dericcrago** [comment]
hi @EricAtORS - you could try using the PPA for a more recent version - https://launchpad.net/~ansible/+archive/ubuntu/ansible

**Comment by felixfontein** [comment]
resolved_by_pr #269

**Comment by felixfontein** [comment]
I plan to create new releases once #269 has been merged. With these releases, the issue should be fixed.

**Comment by felixfontein** [comment]
community.docker 1.10.4 and 2.1.1 have been released which fix this issue.
