### ISSUE TITLE
Support --template-driver for docker_config

### ISSUE THREAD

**Issue by willat8** [ansible-collections/community.docker#332]
##### SUMMARY

The `--template-driver` parameter set to `golang` when creating a docker config means we can create docker configs referencing environment variables, secrets and other information. Support for setting this in the `docker_config` module would be useful.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_config

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by felixfontein** [comment]
This shouldn't be too hard to implement, since Docker SDK for Python offers this: https://docker-py.readthedocs.io/en/stable/api.html#docker.api.config.ConfigApiMixin.create_config
