### ISSUE TITLE
add support for cgroupns

### ISSUE THREAD

**Issue by christf** [ansible-collections/community.docker#338]
##### SUMMARY
Some containers https://github.com/ONLYOFFICE/Docker-CommunityServer/issues/131  - apparently those that run systemd - will require --cgroupns=host to be set. 
This is currently not possible with the docker role. Please consider adding the fature

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION
being able to set 
```
cgroupns: host 
```
woulrd be very useful to run this kind of container.

**Comment by felixfontein** [comment]
`--cgroupns` corresponds to the `CgroupnsMode` host config (judging from the docker-cli sources), but Docker SDK for Python does not (yet) support that.

(And judging the state of the Docker SDK for Python project, I wouldn't hope that it will support it anytime soon... :( )

**Comment by felixfontein** [comment]
(Also there is no role in this collection. We only have modules and plugins.)

**Comment by felixfontein** [comment]
I created an implementation of this in #427 (based on the rewrite #422 of docker_container to use the API directly).
