### ISSUE TITLE
Nightly CI failed because of Docker Hub limitations

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.docker#35]
##### SUMMARY
In this run: https://app.shippable.com/github/ansible-collections/community.docker/runs/68/12/console and two others, CI failed because of [Docker Hub's rate limiting](https://www.docker.com/increase-rate-limits?utm_source=docker&utm_medium=web%20referral&utm_campaign=pull%20limits%20hub%20home%20page&utm_budget=).

``"Error looking for an image named alpine:3.8: 429 Client Error: Too Many Requests (\"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit\")"``

I guess we'll have to reorganize the images a bit, and push/pull some to/from quay.io instead.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
CI

**Comment by WojciechowskiPiotr** [comment]
Or maybe try to contact Docker team/owners/managers directly asking for lifting the limit for us? I think it may be in their own interest and overall cost them nothing. Just a thought...

**Comment by felixfontein** [comment]
@WojciechowskiPiotr that would be possible, but would probably require us to use an account, which makes running things in CI more complicated (credentials need to be handled, login must be done). Making it easier to change the images in use, and using other images, also solves this problem and makes it easier to solve in the future if something similar happens again.

For now I implemented the possibility of making it easier to switch images in #36, and used the same images from ansible/ansible#72698. We're still using two images from Docker Hub (`nginx` and `registry`), but since they are needed a lot less frequently it should be fine to keep them for now.
