### ISSUE TITLE
docker_image: load image without specifying the name

### ISSUE THREAD

**Issue by AssafKatz3** [ansible-collections/community.docker#417]
##### SUMMARY
Currently docker_images module does not allow to load images from a TAR file without specifying the name of the image, which besides is an issue by itself (sometimes You don't know image name upfront) but most importantly does not allow to load multiple images from one tar file

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker_image module

##### ADDITIONAL INFORMATION
"Name" parameter should not be required if load_path is specified (and the name itself should be determined by ansible/docker) or "Name" can persist required but should have some value like "as original" or "as_load"

Use cases:

1. Loading a few images saved in one tar file
2. Loading images for which You don't know the name upfront (for example if You want to get the latest version not knowing exactly what the version is or simply development team is saving images to file and their name are hashed or so)

```
- name: Load images from the archive 
  docker_image:
    name: [some_new_parameter]
    load_path: my_images.tar

```

This issue is still existing (at least at documentation) as was [three years ago](https://github.com/ansible/ansible/issues/43008).

**Comment by felixfontein** [comment]
That's how the `docker_image` module works, and it won't change. If you want to load multiple images from a tar file, or don't know the image name, use the [`docker_image_load` module](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_load_module.html).

**Comment by felixfontein** [comment]
(See also #86.)
