### ISSUE TITLE
Typo in docker doc fragment

### ISSUE THREAD

**Issue by gotmax23** [ansible-collections/community.docker#459]
I found a typo in the the docs. I believe it should be `that` not `hat`. I used Github's Reference in New Issue feature, but I can fill out the whole issue template if you'd like.

https://github.com/ansible-collections/community.docker/blob/03ecea94c08e56dfe8cc97d58b48e89b20a8eb7c/plugins/doc_fragments/docker.py#L288-L290

**Comment by felixfontein** [comment]
No need to fill out the whole form! I created a fix in #460.

**Comment by felixfontein** [comment]
> I used Github's Reference in New Issue feature,

I wasn't aware of that one, really nice indeed!

Thanks for reporting this!
