### ISSUE TITLE
docker_container_exec results missing when used in playbook

### ISSUE THREAD

**Issue by bitsky6** [ansible-collections/community.docker#489]
When I add the module docker_container_exec always get error action/module missing

The rest seems to be working fine
docker_login
docker_container
...
etc 

I am using ansible 2.13.5

**Comment by felixfontein** [comment]
Are you using FQCNs (i.e. `community.docker.docker_container_exec`)? As opposed to many of the other modules, `docker_container_exec` was only added after the Ansible collection split, and thus doesn't have a short-name.

**Comment by bitsky6** [comment]
Hey @felixfontein ,

Thank for that, did not think of that.
I have added the collections path so like this also short name is now recognized for cleaner playbook.

![image](https://user-images.githubusercontent.com/57507315/197582288-4befd627-ce84-4993-aa68-3d726651a354.png)

**Comment by felixfontein** [comment]
@bitsky6 that way it also works. I personally prefer FQCNs over `collections:` though (and ansible-lint will also tell you to use them), since `collections:` can cause surprise problems if names suddenly show up in newer versions of the other collections in that list.
