### ISSUE TITLE
AZP: Some tests skipped under docker 

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/community.docker#49]
##### SUMMARY

Looks like a few integration tests have skip/docker so aren't currently running. Need to check they are running under `remote/rhel`
##### ISSUE TYPE
- Bug Report

**Comment by felixfontein** [comment]
That's only in connection_docker (and the upcoming connection_docker_api, #40). They are both in group 4, and group 4 also uses the RHEL VMs (remotes), so they should run. You can see that both are running when grepping for `Running connection_docker integration test script` and `Running connection_docker_api integration test script` in https://dev.azure.com/ansible/22c50118-fc97-4e5a-9c0d-36527697c9bb/_apis/build/builds/2269/logs/692 and https://dev.azure.com/ansible/22c50118-fc97-4e5a-9c0d-36527697c9bb/_apis/build/builds/2269/logs/754 (the RHEL runs for devel of https://dev.azure.com/ansible/community.docker/_build/results?buildId=2269&view=results).

So everything's fine :)
