### ISSUE TITLE
docker_container exposed_ports is incorrect

### ISSUE THREAD

**Issue by danielo515** [ansible-collections/community.docker#5]
##### SUMMARY
The property published_ports is incorrect. According to the examples an my experience the one that should be used is `ports`

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/latest/collections/community/general/docker_container_module.html#parameter-published_ports

##### ANSIBLE VERSION

```
ansible 2.9.11
  config file = /Users/danielo/mega/ansible/ansible.cfg
  configured module search path = ['/Users/danielo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.11/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
```

I wanted to open a PR to fix it but:

- Don't know where the git repository of the linked docs is
- I don't know which one is the correct one

**Comment by felixfontein** [comment]
Closing since there was no clarification of what the actual problem is.
