### ISSUE TITLE
Splunk Logging Driver splunk-capath: no such file or directory

### ISSUE THREAD

**Issue by cyberglad** [ansible-collections/community.docker#590]
##### SUMMARY
**splunk-capath** is read before volume mount: as a result, it can't find the certificate, bc it's not been mounted yet

driver: "splunk-logging-plugin"
      options:
        splunk-url: "https://xxxxxx"
        splunk-token: "xxxxx"
        splunk-capath: "/etc/nginx/XXX.crt"
        tag: "{{pll}}-xxx-nginx-{{inu}}"
{% endif %}
    volumes:
      - /app/{{platform}}/{{pll}}-xxx-nginx-{{inu}}/config:/etc/nginx

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
splunk logging driver

##### ANSIBLE VERSION

```paste below
2.11
```

##### OS / ENVIRONMENT

rhel 8

##### EXPECTED RESULTS

the certificate path should be taken into account

##### ACTUAL RESULTS

the certificate path is not taken into account
failed to initialize logging driver: error creating logger: error creating splunk logger: open /etc/nginx/xxxxx.crt: no such file or director

**Comment by felixfontein** [comment]
Could you please explain what the splunk logging driver has to do with the community.docker collection?

**Comment by felixfontein** [comment]
@cyberglad ping

**Comment by cyberglad** [comment]
sorry wrong forum
