### ISSUE TITLE
nsenter connection plugin can not dnf update (blocked by SELinux)

### ISSUE THREAD

**Issue by rptaylor** [ansible-collections/community.docker#592]
##### SUMMARY
An ansible task to do dnf updates is blocked by SELinux when using the nsenter connection plugin.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nsenter connection plugin

##### ANSIBLE VERSION

```
ansible [core 2.12.10]
  config file = /root/lsb/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.9 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
  jinja version = 3.0.3
  libyaml = True

```

##### COLLECTION VERSION

```
# ansible-galaxy collection list community.docker

# /usr/lib/python3.10/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 2.6.0  

# /root/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.4.1  

```

##### CONFIGURATION

```
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT
Running in a Fedora 36 podman container on a Almalinux 8.7 host server.

##### STEPS TO REPRODUCE

Start a privileged podman container, for example something like
`sudo podman run --pull=newer --rm -it --pid=host --privileged fedora:36`

 and then:

```
# ansible -c community.docker.nsenter -m dnf -a "state=latest name=*" server.example.org  
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
[WARNING]: Platform linux on host server.example.org is using the discovered Python interpreter at /usr/libexec/platform-python, but future installation of another
Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.12/reference_appendices/interpreter_discovery.html for more
information.
server.example.org | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "failures": [
        [
            "error: failed to exec scriptlet interpreter /bin/sh: Permission denied",
            "error: %prein(samba-common-0:4.16.4-4.el8_7.noarch) scriptlet failed, exit status 127"
        ]
    ],
    "msg": "Failed to install some of the specified packages",
    "rc": 1,
    "results": []
}

```

##### EXPECTED RESULTS
While it may be that the nsenter connection plugin is doing the right thing, it would be good to at least document the limitations preventing it from doing certain Ansible tasks. Is there anything that could be done to make it easier to dnf update with the nsenter connection plugin? E.g. applications usually come packaged with the SELinux rules they need to operate.

##### ACTUAL RESULTS
Same result if I just `nsenter -t 1 -a` and do dnf update:
```
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                     1/1 
  Running scriptlet: samba-common-4.16.4-4.el8_7.noarch                                                                                                                  1/2 
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
error: %prein(samba-common-0:4.16.4-4.el8_7.noarch) scriptlet failed, exit status 127

Error in PREIN scriptlet in rpm package samba-common
  Verifying        : samba-common-4.16.4-4.el8_7.noarch                                                                                                                  1/2 
  Verifying        : samba-common-4.16.4-2.el8.noarch                                                                                                                    2/2 

Failed:
  samba-common-4.16.4-2.el8.noarch                                                     samba-common-4.16.4-4.el8_7.noarch                                                    

Error: Transaction failed
```

```
Feb 23 15:30:14 server.example.org /SetroubleshootPrivileged.py[10630]: failed to retrieve rpm info for /var/lib/selinux/targeted/active/modules/200/container
Feb 23 15:30:14 server.example.org setroubleshoot[10617]: SELinux is preventing /usr/libexec/platform-python3.6 from using the transition access on a process. For >
Feb 23 15:30:14 server.example.org setroubleshoot[10617]: SELinux is preventing /usr/libexec/platform-python3.6 from using the transition access on a process.
                                                                   
                                                                   *****  Plugin catchall (100. confidence) suggests   **************************
                                                                   
                                                                   If you believe that platform-python3.6 should be allowed transition access on processes labeled rpm_scrip>
                                                                   Then you should report this as a bug.
                                                                   You can generate a local policy module to allow this access.
                                                                   Do
                                                                   allow this access for now by executing:
                                                                   # ausearch -c 'platform-python' --raw | audit2allow -M my-platformpython
                                                                   # semodule -X 300 -i my-platformpython.pp
```

**Comment by rptaylor** [comment]
Hmm maybe we could get a SELinux boolean set up to make it easy to enable this.

**Comment by rptaylor** [comment]
Hmm it actually works on the latest fully updated CentOS Stream 8, but not Almalinux 8.

On Almalinux I had container-selinux-2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch
CentOS 8 has container-selinux-2.195.1-1.module_el8.8.0+1254+78119b6e.noarch

I tested downgrading to the older version on CentOS, and the error returned.
On Almalinux I borrowed the newer package from the CentOS repo and this fixed the problem.

So upgrading from container-selinux-2.189 to container-selinux-2.195 when it is available will address this problem.

**Comment by felixfontein** [comment]
> While it may be that the nsenter connection plugin is doing the right thing, it would be good to at least document the limitations preventing it from doing certain Ansible tasks. Is there anything that could be done to make it easier to dnf update with the nsenter connection plugin? E.g. applications usually come packaged with the SELinux rules they need to operate.

I'm not sure there is anything we can do here. The plugin uses nsenter to execute commands. Every restriction that is true for nsenter is also true for this connection plugin. Basically as you wrote:

> Same result if I just `nsenter -t 1 -a` and do dnf update:

**Comment by rptaylor** [comment]
I wanted to document the issue at least, and the new container-selinux package will fix it.

**Comment by rptaylor** [comment]
Looking closer, I found that there is a reproducible problem when ansible and the nsenter connection plugin are used to do a dnf update, which does not occur when doing `nsenter -t 1 -a` and `dnf update -y` . 
I wonder if the selinux rules in container-selinux-2.195 allow the /usr/bin/dnf executable to do the update, but might be blocking ansible from doing the update by interfacing with the DNF python API ?


How to reproduce on latest CentOS 8 Stream:
- Install podman and container-selinux-2.195 or newer
- make sure there are some available updates to apply (dnf downgrade something if needed)
- ` sudo podman run --pull=newer --rm -it --pid=host --privileged fedora:36`
-  `dnf install ansible` in the container
- put "server" in /etc/ansible/hosts
- `ansible -c community.docker.nsenter -m dnf -a "state=latest name=*" server`

There will be SELinux denials:
```
Mar 01 23:27:02 centos8.novalocal /SetroubleshootPrivileged.py[6640]: failed to retrieve rpm info for /var/lib/selinux/targeted/active/modules/200/container
Mar 01 23:27:02 centos8.novalocal setroubleshoot[6622]: SELinux is preventing /usr/libexec/platform-python3.6 from using the transition access on a process. For complete SELinux messages run: sealert -l 7728fb06-3996-48cf-a360-d0f6db6b497e
Mar 01 23:27:02 centos8.novalocal setroubleshoot[6622]: SELinux is preventing /usr/libexec/platform-python3.6 from using the transition access on a process.
                                                        
                                                        *****  Plugin catchall (100. confidence) suggests   **************************
                                                        
                                                        If you believe that platform-python3.6 should be allowed transition access on processes labeled rpm_script_t by default.
                                                        Then you should report this as a bug.
                                                        You can generate a local policy module to allow this access.
                                                        Do
                                                        allow this access for now by executing:
                                                        # ausearch -c 'platform-python' --raw | audit2allow -M my-platformpython
                                                        # semodule -X 300 -i my-platformpython.pp                                                     
```

Sometimes I would still get the same "/bin/sh: Permission denied" errors, but not always. Sometimes the ansible dnf update seems to work and succeeds in updating without producing a failure or stderr. But sometimes I ran into issues indicating the RPMDB got corrupted. I think it depends on which packages are updated and what their postscripts do. Regardless, the consistent thing no matter what is that there are SELinux denials in the log.


If you instead do 
- `nsenter -t 1 -a`
- `dnf update -y`
there are no SELinux error logs.

**Comment by felixfontein** [comment]
You could try running the `dnf` executable with the `ansible.builtin.command` module.

In any case, this looks very much related to SELinux rules and the way Ansible executes modules, but not to the community.docker.nsenter connection plugin.

**Comment by rptaylor** [comment]
Good idea I'll try that as a workaround. Another fix was identified too: https://github.com/containers/container-selinux/commit/018cb36d55edb0a27d2437a2bfe098d1bc412f75
