### ISSUE TITLE
ansible template validation fails with SELinux errors using nsenter connection plugin

### ISSUE THREAD

**Issue by rptaylor** [ansible-collections/community.docker#599]
##### SUMMARY
Please see all the details and reproduction steps here: https://github.com/ansible/ansible/issues/80269
I thought it seemed like an issue with ansible template validation but an Ansible maintainer suggested it was an issue with the nsenter connection plugin; can you tell where the issue is?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nsenter connection plugin

##### ANSIBLE VERSION

```
$ ansible --version
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.10 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
  jinja version = 3.0.3
  libyaml = True
$ rpm -q ansible
ansible-5.9.0-1.fc36.noarch
```

##### COLLECTION VERSION

```
# ansible-galaxy collection list community.docker

# /usr/lib/python3.10/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 2.6.0  
```

##### CONFIGURATION

```
# nothing
```

##### OS / ENVIRONMENT

See linked issue.

##### STEPS TO REPRODUCE

See linked issue.

##### EXPECTED RESULTS

See linked issue.

##### ACTUAL RESULTS

See linked issue.

**Comment by felixfontein** [comment]
I don't really see what the nsenter connection plugin can do about this. @nitzmahone wasn't saying (as I understood it) that this is a problem with the nsenter **connection** plugin, but with the command line tool nsenter itself (which the plugin is using). The nsenter connection plugin basically prepends the command ansible wants to run with `nsenter` and some options - see https://github.com/ansible-collections/community.docker/blob/main/plugins/connection/nsenter.py#L103-L113 for what exactly.

**Comment by nitzmahone** [comment]
Yeah- after thinking about it some more, ultimately this is a really complex halting problem that doesn't necessarily have a generic solution. Having `template` blindly `chcon` its tempfile to match the destination file *might* solve this particular problem, but depending on the system policy and enforcement mode, could just as easily lead to a tempfile that Ansible can no longer access or clean up :laughing: . 

Off the top of my head, if you know that's *not* the case, you could add a couple of intermediate steps to template out to a tempfile, `chcon` the tempfile yourself to match the target, then call `iptables-restore` on the tempfile, and wrap it in a `block` with an `always` to clean up the tempfile afterwards. It's not as handy as having `template` do it all for you, but should hopefully get you past the hump.

Given how (relatively) difficult testing the SELinux bits are, I'm guessing there wouldn't be a lot of appetite from the core team to add extra knobs to control the labeling of the tempfile inside `template`/`copy`/others...

**Comment by nitzmahone** [comment]
(suggest we move this back to https://github.com/ansible/ansible/issues/80269, which I've reopened)
