### ISSUE TITLE
docker_swarm: removing a manager does not work

### ISSUE THREAD

**Issue by bluikko** [ansible-collections/community.docker#601]
##### SUMMARY

Removing a manager from swarm following the listed example does not work:
```yaml
- name: Remove node from swarm
  community.docker.docker_swarm:
    state: remove
    node_id: mynode
```

This results in error even with `force: true` specified:
```console
  msg: 'Can not remove the node from the Swarm Cluster: 400 Client Error for http+docker://localhost/v1.42/nodes/x?force=True: Bad Request ("rpc error: code = FailedPrecondition desc = node x is a cluster manager and is a member of the raft cluster. It must be demoted to worker before removal")'
```

Either there needs to be an additional option `state: demote` so that a manager can be first demoted and then removed, or `state: remove` with `force: true` needs to be modified to first demote if the node is a manager.

I plan to look into adding a `state: demote` to the module so please feedback which of the above 2 approaches would be preferable.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_swarm

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/bin/ansible
  python version = 3.9.14 (main, Jan  9 2023, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/home/ansible/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/share/ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.4.3
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

EL9

##### STEPS TO REPRODUCE

```yaml
- name: Remove node from swarm
  community.docker.docker_swarm:
    state: remove
    node_id: mynode
```

##### EXPECTED RESULTS

A node is removed from swarm.

##### ACTUAL RESULTS

Node is not removed and error is displayed.

```paste below
  msg: 'Can not remove the node from the Swarm Cluster: 400 Client Error for http+docker://localhost/v1.42/nodes/x?force=True: Bad Request ("rpc error: code = FailedPrecondition desc = node x is a cluster manager and is a member of the raft cluster. It must be demoted to worker before removal")'
```

**Comment by bluikko** [comment]
Seems quite straightforward to implement `state: demote`.

Now I would also like to add functions for managing node activation status (`drain` / `active`).  
Then the question becomes: should there instead of `state: demote` be another option for example `state: update` that is used to:
- Demote/promote manager/worker.
- Drain/Active a node.

Or should there be 2 more `state`s, i.e. `state: drain` and `state: active`?

Feedback appreciated before I go too far down a wrong path!

**Comment by bluikko** [comment]
I see that the "demote" and "drain"/"activate" functionality is implemented in the `docker_node` module.

So I believe only documentation needs to be updated and there is no need for functional changes?

**Comment by felixfontein** [comment]
I'm not using Docker Swarm and are not familiar with it, but yeah, updating/extending the docs sounds like a good idea.

**Comment by bluikko** [comment]
> updating/extending the docs sounds like a good idea

I was thinking about simply adding a reference to the `docker_node` module and that it can be used to demote managers before removal.

I guess it should use the `M(FQCN)` markup?

**Comment by felixfontein** [comment]
Yes, `M(community.docker.docker_node)` is the correct markup.
