### ISSUE TITLE
Failed to import the required Python library (requests) 

### ISSUE THREAD

**Issue by kennyphampoway** [ansible-collections/community.docker#606]
##### SUMMARY
Cannot load any docker module, The error message is 

 **"msg": "Failed to import the required Python library (requests) on bde-dev-dev3.vdev.bde.net's Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"**

Requests is installed, ansible_python_interpreter is set. 

Please help. I cant really find the root of the issue

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
 ansible --version
ansible [core 2.11.12]
  config file = /home/sandbox/test_docker_ansible/ansible.cfg
  configured module search path = ['/home/sandbox/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sandbox/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/sandbox/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/sandbox/.local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.3
  libyaml = True

##### COLLECTION VERSION
ansible-galaxy collection list community.docker
show 
# /home/sandbox/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.4.3

# /home/sandbox/.local/lib/python3.6/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 1.10.2

##### PYTHON VERSION
/home/sandbox/.local/lib/python3.6/site-packages

shows

requests
requests-2.27.1.dist-info

##### ANSIBLE PLAYBOOK (test.yaml)
- name: Build container image
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  become: yes
  tasks:
    - name: test docker image
      community.docker.docker_image:
            name: image_base:latest
            source: build
            build:
                path: /tmp/container

##### OS / ENVIRONMENT
CentOS 

##### STEPS TO REPRODUCE
ansible-playbook test.yaml   -vvvvv
show this error

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_community.docker.docker_image_payload_a83fkhbu/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/_import_helper.py", line 24, in <module>
    from requests import Session  # noqa: F401, pylint: disable=unused-import
ModuleNotFoundError: No module named 'requests'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "archive_path": null,
            "build": {
                "args": null,
                "cache_from": null,
                "container_limits": null,
                "dockerfile": null,
                "etc_hosts": null,
                "http_timeout": null,
                "network": null,
                "nocache": false,
                "path": "/tmp/container",
                "platform": null,
                "pull": false,
                "rm": true,
                "target": null,
                "use_config_proxy": null
            },
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "debug": false,
            "docker_host": "unix://var/run/docker.sock",
            "force_absent": false,
            "force_source": false,
            "force_tag": false,
            "load_path": null,
            "name": "image_base:latest",
            "pull": null,
            "push": false,
            "repository": null,
            "source": "build",
            "ssl_version": null,
            "state": "present",
            "tag": "latest",
            "timeout": 60,
            "tls": false,
            "tls_hostname": null,
            "use_ssh_client": false,
            "validate_certs": false
        }
    },
    "msg": "Failed to import the required Python library (**requests**) on sandbox.net's Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on **ansible_python_interpreter**"
}

##### ACTUAL RESULTS

```paste below

```

**Comment by felixfontein** [comment]
You use `become: yes`, so most likely the module will be run as `root` (depending on your ansible-core configuration of course), which means the module will not be run as your local user and thus does not have access to libraries only installed for your user.

**Comment by kennyphampoway** [comment]
thanks, felixfontein. The issue seems to work after removing "become: yes". 
Is there a way to let a module be accessible by all users?

**Comment by kennyphampoway** [comment]
Tge

**Comment by kennyphampoway** [comment]
Close the issue. Felixfontein's suggestion fixes the issue

**Comment by felixfontein** [comment]
Installing requests as root will make it available for every user on that system.

**Comment by kennyphampoway** [comment]
it works with all users following felixontein's suggestion.

**Comment by felixfontein** [comment]
Thanks for reporting back! Closing since this is resolved.
