### ISSUE TITLE
Fix documentation for docker_swarm node_cert_expiry param

### ISSUE THREAD

**Issue by cen1** [ansible-collections/community.docker#622]
##### SUMMARY

Page in question: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_swarm_module.html

It is very unclear what `node_cert_expiry` (int) is supposed to be. Months? Years? Miliseconds?

The docs says the default is `3months` which is another weirdly formatted string. Is this param actually supposed to be a string and parsed?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
docker_swarm

**Comment by felixfontein** [comment]
Well, the documentation of the corresponding Docker SDK for Python parameter simply says: `Automatic expiry for nodes certificates.`, with no further information either. The parameter seems to correspond to the API value `NodeCertExpiry`. The API spec also says (https://docs.docker.com/engine/api/v1.42/#tag/Swarm, https://docs.docker.com/engine/api/v1.42/#tag/Swarm/operation/SwarmUpdate): `The duration node certificates are issued for.`. The Update Swarm API entry has an example with value `7776000000000000`. If that value is interpreter as nanoseconds, it yields almost 6 years. So my **guess** would be that this is in nanoseconds.

**Comment by felixfontein** [comment]
On the Go side, `NodeCertExpiry` is defined as `NodeCertExpiry time.Duration `json:",omitempty"``, and `time.Duration` is defined as `type Duration int64` in Golang's standard library. So my guess with nanoseconds is probably true. (I know too little about Go to be able to fully confirm this though.)

**Comment by Ajpantuso** [comment]
Yes a single unit of `time.Duration` in Go is a nanosecond.
Ref: https://pkg.go.dev/time#Duration

**Comment by felixfontein** [comment]
PR: #623
