### ISSUE TITLE
Add support for docker compose config

### ISSUE THREAD

**Issue by lonix1** [ansible-collections/community.docker#639]
##### SUMMARY

Please support compose's [`config` option](https://docs.docker.com/engine/reference/commandline/compose_config).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker compose

##### ADDITIONAL INFORMATION

It is used for validating compose files.

```console
docker compose config --file /foo/bar/docker-compose.yml config -q
```

**Comment by felixfontein** [comment]
The community.docker.docker_compose module has been removed from today's 4.0.0 release. If you are still using it, please upgrade to community.docker.docker_compose_v2, which no longer uses the End of Life versions Docker Compose 1.x.y, but Docker's Compose plugin (version 2.x.y range).
