### ISSUE TITLE
docker_container: IPv6 port validation doesn't allow for interface specification.

### ISSUE THREAD

**Issue by Kristof-Mattei** [ansible-collections/community.docker#65]
https://github.com/ansible-collections/community.docker/blob/c7a3d9f057f853c99028430f123a26effe433b03/plugins/modules/docker_container.py#L1732

My link local address is of the format `[fe80::d65d:daaf:fe1e:11a7%eno1]`, and I'm trying to use that in a port map as follows:

```
        ports:
          - "[fe80::d65d:dfff:fe1e:11a8%eno1]:53:53/tcp"
```

But the regex doesn't accept this, even though it's a valid bind.

Manually creating the container with that port mapping does work.

**Comment by felixfontein** [comment]
Do you happen to have a link where this syntax is documented?

**Comment by felixfontein** [comment]
Is it the syntax from RFC 4007 (https://tools.ietf.org/html/rfc4007#section-11)?

**Comment by felixfontein** [comment]
resolved_by_pr #66
