### ISSUE TITLE
Allow --output or arbitrary arguments for docker build

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible-collections/community.docker#67]
##### SUMMARY

I am using `docker_image` to build an image from a Dockerfile.
My end goal is to compile something inside the container, and then copy the binaries to the host, without all the dependencies.
I've got this working at the moment with:

* build image
* start container from image
* shell: `docker cp`
* stop container

The docker command now includes a `--output` option for `docker build`, to do all this in one command.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_image

##### ADDITIONAL INFORMATION

The module has `build.args`, but this is for arguments to be used *inside* the dockerfile, which is different to what I want.

I would be happy with a general way to pass arbitrary arguments to `docker build`. Something specific to `--output` would be nice, but then you'd have to worry about idempotency in the case where the `Dockerfile` is unchanged but the target directory has changed since the last run.

**Comment by felixfontein** [comment]
Please remember that almost all docker modules DO NOT call the docker CLI tools. They use the [Docker SDK for Python](https://docker-py.readthedocs.io/en/stable/). If the SDK supports that, we can add support for it, too.

**Comment by felixfontein** [comment]
Also docker_image's image build is not really idempotent IIRC, I think it only checks whether the destination image already exists.

**Comment by mdavis-xyz** [comment]
Why doesn't Ansibullbot know which files I'm talking about?

I thought the `docker build` command is idempotent. If you run it twice in the terminal, it says it's using a cache the second time. 

For the SDK, I didn't know that.
It looks like the [high-level method](https://docker-py.readthedocs.io/en/stable/images.html?highlight=build#docker.models.images.ImageCollection.build) does not support this, and the [lower level](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.build.BuildApiMixin.build) one doesn't either.

I guess I'll just close this feature request and use a `shell` task.

**Comment by felixfontein** [comment]
In case you didn't notice it, I moved this issue to the correct repository. The docker modules are no longer part of the community.general repository (they will be removed in 2.0.0), so it's no surprise the bot doesn't find anything. 

Also, I'm talking about the `docker_image` module, not about the CLI. The module only rebuilds an image if forced to do so, or if the image does not exist (https://github.com/ansible-collections/community.docker/blob/main/plugins/modules/docker_image.py#L400-L412).
