### ISSUE TITLE
Slightly misleading docs about capabilities of `docker_stack_info` module

### ISSUE THREAD

**Issue by enpaul** [ansible-collections/community.docker#690]
##### SUMMARY
The wording of the documentation for the `community.docker.docker_stack_info` module implies that the module can be used to retrieve information on a single or specific stack from the host, however this is not the case:

From the [short description](https://github.com/ansible-collections/community.docker/blob/main/plugins/modules/docker_stack_info.py#L16C20-L16C56)

> Return information on a docker stack

_Can be read as "return information on a specific stack"_

From the [return value documentation](https://github.com/ansible-collections/community.docker/blob/main/plugins/modules/docker_stack_info.py#L27):

>  List of dictionaries containing the list of stacks or tasks associated to a stack name.

_Can be read as "lsit of stacks or tasks associated to a single or provided stack name"_

I'd propose either updating the documentation to reflect that the module only returns information about all stacks or update the functionality to allow passing an optional `name` parameter that allows a user to limit the output contents to a single stack. Either solution (docs update or functionality update) I would be more than happy to implement if people would be ok with that.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
`plugins/modules/docker_stack_info.py`

##### ANSIBLE VERSION

```
ansible [core 2.15.4]
  config file = ./ansible.cfg
  configured module search path = ['.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ./.venv/lib/python3.11/site-packages/ansible
  ansible collection location =./.ansible
  executable location = ./.venv/bin/ansible
  python version = 3.11.5 (main, Aug 28 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)] (./.venv/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

**Comment by felixfontein** [comment]
I think both (updating docs, or adding an optional `name` option) is OK.

CC @imjoseangel who authored the module.

**Comment by enpaul** [comment]
After looking at this, I think the `docker_stack_task_info` module provides the functionality I was looking for with the hypothetical `name` parameter. I've submitted a pull request [here](#693) to add some clarifying documentation to this module to reflect that.

**Comment by felixfontein** [comment]
Cool. I think then this one can be closed :) (if that was wrong, please tell me, I'll reopen)
