### ISSUE TITLE
Multi-line content support in docker_container_copy_into

### ISSUE THREAD

**Issue by onknows** [ansible-collections/community.docker#692]
##### SUMMARY
Enhance docker_container_copy_into to support multi-line content.

##### ISSUE TYPE
The current implementation of the `docker_container_copy_into module` restricts the `content` field to single-line text only. When multi-line content is provided, the module processes it by removing newline characters, resulting in a single-line file. This limitation diminishes the module's utility for handling common multi-line files.

##### COMPONENT NAME
docker_container_copy_into

##### ADDITIONAL INFORMATION
The proposed enhancement aligns with user expectations and real-world use cases, making the `docker_container_copy_into` module a more powerful and flexible tool for managing multi-line files within Docker containers.

**Comment by felixfontein** [comment]
I'm not sure how you got that impression, but that's not true. You can have multi-line text in there, it's even tested and verified in the integration tests.

**Comment by felixfontein** [comment]
Example: https://github.com/ansible-collections/community.docker/blob/main/tests/integration/targets/docker_container_copy_into/tasks/tests/content.yml#L730-L732 - https://github.com/ansible-collections/community.docker/blob/main/tests/integration/targets/docker_container_copy_into/tasks/tests/content.yml#L772

**Comment by onknows** [comment]
My mistake, I accidentally passed not a string but a dict which then got transformed to single line string.
