### ISSUE TITLE
docker_swarm_service does not expose --replicas-max-per-node

### ISSUE THREAD

**Issue by nicholasamorim** [ansible-collections/community.docker#7]
##### SUMMARY
docker_swarm_service does not expose the `--replicas-max-per-node` that is very useful especially when running services that might need HA in a more strict manner (databases, etc)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_swarm_service

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by b2az** [comment]
just here to tell you, that i also need this in my playbooks.

**Comment by WojciechowskiPiotr** [comment]
> just here to tell you, that i also need this in my playbooks.

Hi, the docker-py maintainers review my change proposal, so I how we can marge it soon. I have the patch for docker_swarm_service ready.

**Comment by WojciechowskiPiotr** [comment]
My change (https://github.com/docker/docker-py/pull/2741) has been merged so as soon as the next version of docker-py is released I will implement this feature in `docker_swarm_service`

**Comment by WojciechowskiPiotr** [comment]
FYI my change in docker-py will be included in release 4.5.0 so we have to wait until it is released.

**Comment by hartwork** [comment]
> FYI my change in docker-py will be included in release 4.5.0 so we have to wait until it is released.

While [not mentioned in the change log of docker-py 4.4.3](https://github.com/docker/docker-py/issues/2774) I can confirm that https://github.com/docker/docker-py/issues/2774 has just hit PyPI in release 4.4.3 already yesterday.

**Comment by felixfontein** [comment]
As long as they don't remove it again in 4.4.4, I guess we can start using it ;-)

**Comment by WojciechowskiPiotr** [comment]
Ok, I saw it on the list for the 4.5.0 release but it is even better it was included in 4.4.3 even by this small mistake :) In such case, I will prepare my change for community.docker shortly.

**Comment by felixfontein** [comment]
This has been implemented in #92 and will be available in the 1.3.0 release.
