### ISSUE TITLE
IPv6 port mapping broken with docker 20.10.2

### ISSUE THREAD

**Issue by seblu** [ansible-collections/community.docker#70]
##### SUMMARY
The `docker_container` module set an IP**v4** as [default host](https://github.com/ansible-collections/community.docker/blob/5072b7d1c31bacb3b06174d1f4a39d1d4afc7950/plugins/modules/docker_container.py#L1673) for `published_ports`.
Since the last version of docker (20.10.2) and recent changes (see [here](https://github.com/moby/libnetwork/issues/2607)), `0.0.0.0` doesn't bind on IPv6 anymore.

So, containers defined like the following loose their dual stack binding when upgrading to docker 20.10.2. If containers were defined with the docker cli, upgrade would be transparent.
```yaml
- docker_container:
    image: nginx
    name: foo
    published_ports:
    - 8080:80
```

A user side workaround could to be force definition of a listening IPv6 host like the following.
This require to known if host is supporting IPv6 instead of having it configured automatically depending of the host support of an IPv6 stack.
N.B: I didn't find a way to push an empty string as host in `published_ports`.
```yaml
    published_ports:
    - "0.0.0.0:8080:80"
    - "[::]:8080:80"
```

The difference between containers can be seen with the following commands:
```
# create a bar container from cli
$ docker run --publish 8081:80 --name bar -d nginx

$ docker inspect bar -f='{{.HostConfig.PortBindings}}'        
map[80/tcp:[{ 8081}]]

$ docker inspect foo -f='{{.HostConfig.PortBindings}}'
map[80/tcp:[{0.0.0.0 8080}]]
```

##### SOLUTION

I suggest to mimic the docker cli behavior and change the default Host to an empty string.
This way, when users doesn't set an host for `published_ports`, **dockerd** chooses the correct binding.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = /home/seblu/scm/infra/ansible.cfg
  configured module search path = ['/home/seblu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
```
##### OS / ENVIRONMENT

Arch Linux

##### STEPS TO REPRODUCE
- Have an IPv6 host
- Upgrade to docker > 20.10

A simple container like this is enough.

```yaml
- docker_container:
    image: nginx
    name: foo
    published_ports:
    - 8080:80
```

##### EXPECTED RESULTS
Docker container should be bound to IPv6 host addresses.
```
$ ss -tulpn|grep docker-proxy
tcp   LISTEN 0      4096                            0.0.0.0:8080       0.0.0.0:*    users:(("docker-proxy",pid=678243,fd=4))                                                                                                           
tcp   LISTEN 0      4096                               [::]:8080          [::]:*    users:(("docker-proxy",pid=678248,fd=4))

$ curl http://[2001:ac1d:bee:face:beef::1]:8080
<!DOCTYPE html>
<html>
...
```
This ouput is with docker > 20.10. With older version the binding is on `*:8080`.

##### ACTUAL RESULTS
```
$ ss -tulpn|grep docker-proxy
tcp   LISTEN 0      4096                            0.0.0.0:8080       0.0.0.0:*    users:(("docker-proxy",pid=682889,fd=4))                                                                                                           
                                                                                     
$ curl http://[2001:ac1d:bee:face:beef::1]:8080
curl: (7) Failed to connect to 2001:ac1d:bee:face:beef::1 port 8080: Connection refused


```

**Comment by felixfontein** [comment]
Simply switching the default IP to `''` breaks backwards compatibility: containers started with a version which used an IP address (like `0.0.0.0`) will be restarted. But what we could do is offer to set the default IP as a module option, and allow an empty string as a possible choice.

**Comment by seblu** [comment]
Restarting a container is a backward compatibility breakage/issue?

Adding a default host binding string looks good too, except it will introduce a new difference between the cli and the module.

**Comment by felixfontein** [comment]
I created PR #71 which adds an option `default_host_ip`. If you use that and set it to `""` (empty string), it should work for you.

**Comment by felixfontein** [comment]
@Henkhogan the docker_container module works totally different from the docker_swarm_service module. The latter does not do magic string transformations for idempotency checks. So something like a global option `default_host_ip` doesn't make sense for docker_swarm_service.
