### ISSUE TITLE
Create `docker_plugin` module

### ISSUE THREAD

**Issue by Cougar** [ansible-collections/community.docker#74]
##### SUMMARY

Ansible module for [Docker plugin](https://docs.docker.com/engine/extend/) management is missing. It would be nice to use special module instead of `command` or `shell` module where it is almost impossible to do any idempotency checks.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`docker_plugin` would be the good candidate for this plugin name.

##### ADDITIONAL INFORMATION

For the reference, this is the usage info for `docker plugin` command:

```
Usage:  docker plugin COMMAND

Manage plugins

Commands:
  create      Create a plugin from a rootfs and configuration. Plugin data directory must contain config.json and rootfs directory.
  disable     Disable a plugin
  enable      Enable a plugin
  inspect     Display detailed information on one or more plugins
  install     Install a plugin
  ls          List plugins
  push        Push a plugin to a registry
  rm          Remove one or more plugins
  set         Change settings for a plugin
  upgrade     Upgrade an existing plugin

Run 'docker plugin COMMAND --help' for more information on a command.
```

Docker [Python SDK](https://pypi.org/project/docker/) already implements all necessary [hooks](https://github.com/docker/docker-py/blob/master/docker/api/plugin.py).

**Comment by felixfontein** [comment]
There used to be a PR implementing such a module (ansible/ansible#52643) but it never completed. Might be useful as a starting point (including all the open review comments).

**Comment by sakar97** [comment]
Hi @felixfontein Can I start working on the `docker plugin` module. It may take a day or two to complete it as I already check the previous closed PR and discussions you guys had.

**Comment by felixfontein** [comment]
@sakar97 as nobody else volunteered so far, feel free to work on that :)

**Comment by felixfontein** [comment]
resolved_by_pr #95
