### ISSUE TITLE
[feature] docker_compose_v2 restart specific service

### ISSUE THREAD

**Issue by davordbetter** [ansible-collections/community.docker#757]
##### SUMMARY

It would be very useful to have same functionality as v1 version to be able to restart only specific service.

docker_compose (v1)
`Use with state present to restart all containers defined in the Compose file.
If services is defined, only the containers listed there will be restarted.`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_compose_v2

**Comment by felixfontein** [comment]
This should be fixed by #758.
