### ISSUE TITLE
Add 'platform' option when pulling in docker_image

### ISSUE THREAD

**Issue by ondrejmo** [ansible-collections/community.docker#79]
##### SUMMARY

It would be handy it was possible to specify platform when pulling an image. Currently when pulling multiarch image that doesn't have a special tag for each architecture it automatically starts pulling the image with architecture of userspace and there's no way to override this behaviour other than using cli:

```yaml
- command:  docker pull --platform=linux/arm64 minio/minio:RELEASE.2021-01-16T02-19-44Z
```

- i.e. when on Raspbian with aarch64 kernel and armv7 userspace, it pulls armv7 image and fails if it doesn't exist, manual override using `--platform arm64` is needed to fix it, but `docker_image` doesn't support `platform` option when pulling

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker_image

##### ADDITIONAL INFORMATION

- Related issue: https://github.com/ansible-collections/community.docker/issues/22

**Comment by felixfontein** [comment]
resolved_by_pr #89
