### ISSUE TITLE
Expose the option to wait for docker_compose_v2 "up"

### ISSUE THREAD

**Issue by iay** [ansible-collections/community.docker#794]
##### SUMMARY

`docker compose` has an option `--wait` which causes the command to wait until the project is up and healthy.

I propose exposing this through the `docker_compose_v2` module.
 
##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

community.docker.docker_compose_v2

##### ADDITIONAL INFORMATION

Currently if you use the module to start a compose project, the task completes immediately. This means that you don't know whether the containers in the project are stable, only that they have been started. The `--wait` option on `docker compose up` allows you to wait until any containers defining health checks are passing those checks. This means that your *next* task can reliably *make use of* the running containers.

**Comment by felixfontein** [comment]
#796 implements this.
