### ISSUE TITLE
ansible-doc docker_compose_v2: was not found

### ISSUE THREAD

**Issue by x70b1** [ansible-collections/community.docker#801]
##### SUMMARY

```
$ ansible-doc docker_compose_v2
[WARNING]: docker_compose_v2 was not found
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_compose_v2

##### ANSIBLE VERSION
```
ansible [core 2.16.3]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/root/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION
```
# /root/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.8.0

# /root/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 3.7.0
```

##### CONFIGURATION
```
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

Was tested on Arch and Debian.

##### STEPS TO REPRODUCE

Run `ansible-doc docker_compose_v2` or use `docker_compose_v2` it in a Playbook/Role.

##### EXPECTED RESULTS

It should resolve.

##### ACTUAL RESULTS

It seems like `docker_compose_v2` is not able to resolve. I have actually no idea how this mapping works. The collection `community.docker` is installed anyway.

Some of the modules are working like `docker_compose` or `docker_image`. Some others are not working like `docker_compose_v2`, `docker_compose_v2_pull`, `docker_image_pull`.

I know that it works with the full path `community.docker.docker_compose_v2`. But as this module will probably get some attention in the future it wouldn't be bad to be able to resolve it similarly to the previous `docker_compose v1` module.

**Comment by felixfontein** [comment]
You need to use the module's FQCN to reference it: `community.docker.docker_compose_v2`. Short names only work for modules that were already around in Ansible 2.9. This will never change as the routing table for short names is part of ansible-core and is permanently frozen.

**Comment by x70b1** [comment]
Oh thanks! That is good background knowledge. 

Well if there will never be a solution for this then I think we can close this already?

**Comment by felixfontein** [comment]
Yes, it's probably best to close this. Thanks!
