### ISSUE TITLE
docker_compose_v2: Pull always check behavior to ignore pulls

### ISSUE THREAD

**Issue by saibotk** [ansible-collections/community.docker#802]
##### SUMMARY
I am using `pull: always` to ensure that docker images that have been rebuilt on the same tag are also always pulled.
But with the pull option set to always, the module will always report a change. I think we might be able to detect if it has actually pulled something or not via the output.

Ideally the step should only be marked as changed, when the containers were recreated. 
I saw that you, @felixfontein, already did something similar in #797, can we maybe introduce that to the docker_compose_v2 module too?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker_compose_v2

Thanks! 
And huge thanks for migrating to compose v2! I could finally remove all the ugly workarounds for the python library installation <3 you're amazing.

**Comment by felixfontein** [comment]
The kind of checks used for docker_container won't work here since the output is usually not sufficient. But considering `Pulling` only when a container is (re-)created is a good idea, that should work.

**Comment by felixfontein** [comment]
#803 fixes this.

**Comment by saibotk** [comment]
Amazing thank you so much for the quick implementation ❤️
