### ISSUE TITLE
docker_container_exec env parameter does not propagate environment

### ISSUE THREAD

**Issue by samuel-emrys** [ansible-collections/community.docker#805]
##### SUMMARY
When attempting to inject environment variables into the command executed by `docker container exec` using the `env` dictionary parameter, the environment variables are not injected. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`docker_container_exec`

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.3]
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.11.1 (main, Feb  7 2023, 23:37:10) [Clang 15.0.7 ] (/home/user/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list community.docker

# /home/user/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 3.7.0
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
CONFIG_FILE() = /home/user/.ansible.cfg
EDITOR(env: EDITOR) = vim
HOST_KEY_CHECKING(/home/user/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Master node: Arch Linux
Managed node:

```
$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/

$ cat /proc/version
Linux version 6.5.11-7-pve (build@proxmox) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z)
``` 

##### STEPS TO REPRODUCE

This is a sample playbook to replicate:

```yaml
---
    - name: test environment
      community.docker.docker_container_exec:
        container: runner1
        command: echo "$ENV1"
        env:
          ENV1: "Hello, World!"
```

##### EXPECTED RESULTS

```
TASK [test environment] ********************************************************                                                           
changed: [192.168.1.20] => {"changed": true, "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "Hello, World!", "stdout_lines": ["Hello, World!"]}
```

##### ACTUAL RESULTS

```
TASK [test environment] ********************************************************                                                           
changed: [192.168.1.20] => {"changed": true, "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "$ENV1", "stdout_lines": ["$ENV1"]}
```

**Comment by felixfontein** [comment]
If your command would run as you expect it to run, it should print an empty string, as `ENV1` is not defined. Since it prints `$ENV1` it indicates that no variable expansion happens.

Did you try running `/bin/sh -c "echo $ENV1"` instead?

**Comment by samuel-emrys** [comment]
Huh. Yes, that has solved it. I'm not sure I understand the reason why this makes a difference - I would have assumed this would execute in a shell on the container. Regardless, I think this would make an excellent addition to the examples.

Thanks for that!

**Comment by felixfontein** [comment]
If you run `echo $ENV1`, it will look for `echo` on `$PATH`, and if it finds an executable (which it probably does), runs that executable with `$ENV1` as the parameter. As usually the shell evaluates variables, and not the `echo` binary, the `echo` binary just outputs its parameter, which happens to be the string `$ENV1`.

If you execute `/bin/sh -c "echo $ENV1"`, you ask that the `/bin/sh` executable is run with parameters `-c` and `echo $ENV1`. In this case, `/bin/sh` (which is a shell) is told to run `echo $ENV1`, and as it is a shell it evaluates variables.

If you run `docker exec runner1 echo '$ENV1'` you'll get the same result BTW, that `$ENV1` is printed on stdout. But if you run `docker runner1 foo /bin/sh -c 'echo $ENV1` you should get the expected output. (In case you wonder, I'm using single quotes instead of double quotes here to make sure the shell you run `docker exec` in doesn't evaluate the variable already.)

**Comment by felixfontein** [comment]
#806 adds a note to the module.

**Comment by samuel-emrys** [comment]
@felixfontein I've had some time to think about what's confusing about the current interface. I think it's that I expect it to function in the same way as the `ansible.builtin.command` module, that is:

```yaml
    - name: test environment
      ansible.builtin.command:
        argv:
          - docker
          - container
          - exec
          - runner1
          - echo
          - $ENV1
      environment:
        ENV1: "Hello, World!"
```
which works as expected - presumably the environment substitution happens on the host rather than the container though. Is there any way to bring the interface of `docker_container_exec` in line with this?

**Comment by felixfontein** [comment]
The `command` module uses `AnsibleModule.run_command()`, which by default evaluates environment variables and `~` even when not passing the command through a shell (https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L1806). (ansible-core 2.16 finally made this configurable: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html#parameter-expand_argument_vars)

> Is there any way to bring the interface of `docker_container_exec` in line with this?

There are ways to do this (at least optionally - it should never be the default behavior), but it's quite some work - you basically have to inspect the container first to get hold of its env variables and things like `$HOME`, and then manually process them and `~`.

In any case, I don't plan to implement it.
