### ISSUE TITLE
Deprecate docker_compose module (and remove it from community.docker 4.0.0)?

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.docker#823]
##### SUMMARY
Right now the old docker_compose module, which relies on Docker Compose v1, is more troublesome to actually test since it neither works with Docker SDK for Python 7+ nor with Docker 26+. (It has been End of Life since July 2022: https://github.com/docker/compose/commit/30fcb72cf3b136598883752edfa6ea4f3b8643d4.) Right now we still have some VM targets where tests for it run, but eventually they will no longer be available.

I'm proposing to deprecate the module and remove it from the next major release (potentially for this fall?).

Users who need to stick to Docker Compose v1 for whatever reason can still use older versions of the collection (including community.docker 3.x.y), which will get updates for some more time (community.docker 2.x.y still gets occasional bugfixes for example, even though 3.0.0 has been available since August 2022).

If there are features that are currently only supported by the docker_compose module, but not by the docker_compose_v2* modules, I guess it's easier to support these features than to keep maintaining the docker_compose module.

Thoughts? Data points (like active usages of the docker_compose module)?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_compose

**Comment by felixfontein** [comment]
I created a PR to implement the deprecation (#833). The existence of that PR does not mean that it will get merged, I'm still waiting for feedback here.

**Comment by pguinet** [comment]
It's only after finding that docker_compose is no more working with Docker 26 that I discovered the existence of docker_compose_v2 module. 
Google search with "ansible docker compose" only shows docker_compose. Even with "ansible docker compose v2". 
So there should be something to do with Google search before to remove docker_compose. 
By the way I'm hundred per cent in favor on removing docker_compose. I'd like to know the existence of docker_compose_v2 when I started using it 6 month ago.

**Comment by felixfontein** [comment]
> Google search with "ansible docker compose" only shows docker_compose. Even with "ansible docker compose v2".
> So there should be something to do with Google search before to remove docker_compose.

I personally don't use Google. I just checked with DuckDuckGo (my default search engine) and when searching for "ansible docker compose", it shows the v2 module as the second or third hit, and when searching for "ansible docker compose v2" it shows it at the top.

I guess over time also Google's search will improve here.

> By the way I'm hundred per cent in favor on removing docker_compose. I'd like to know the existence of docker_compose_v2 when I started using it 6 month ago.

6 months ago that module didn't exist BTW, it only got added in January of this year :)

**Comment by felixfontein** [comment]
If nobody objects or provides at least some hint of need for the old module, I'll merge the deprecation PR by the end of this week.
