### ISSUE TITLE
docker_compose_v2: Cannot parse event from line "mount of type `volume` should not define `bind` option"

### ISSUE THREAD

**Issue by timocov** [ansible-collections/community.docker#846]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.docker.docker_compose_v2`

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.5]
  config file = /home/timocov/projects/home-server/ansible.cfg
  configured module search path = ['/home/timocov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/timocov/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/timocov/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.7.0

# /usr/lib/python3/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 3.8.1
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/timocov/projects/home-server/ansible.cfg
DEFAULT_HOST_LIST(/home/timocov/projects/home-server/ansible.cfg) = ['/home/timocov/projects/home-server/hosts.yml']
```

##### OS / ENVIRONMENT

Ansible host OS: Ubuntu 22.04.4 LTS (wsl)
Target OS: Ubuntu 22.04.4 LTS 
Docker Compose version 2.20.2+ds1-0ubuntu1~22.04.1

##### STEPS TO REPRODUCE

Not sure what the steps are to be honest. I tried to run deploy again but the warning went away. I tried to deploy manually by using `docker compose` but it is all good too...

##### EXPECTED RESULTS

No warnings.

##### ACTUAL RESULTS

```paste below
[WARNING]: Cannot parse event from line: 'time="2024-05-03T23:54:56+01:00" level=warning msg="mount of type `volume` should not define `bind` option"'. Please report this at https://github.com/ansible-
collections/community.docker/issues/new?assignees=&labels=&projects=&template=bug_report.md
```

https://github.com/docker/compose/blob/9c0b92259737c0baf886619517c3222626c2a247/pkg/compose/create.go#L1113

**Comment by felixfontein** [comment]
Code for parsing this warning was added to [community.docker 3.8.1](https://github.com/ansible-collections/community.docker/blob/main/CHANGELOG.md#bugfixes-1), but you manually installed community.docker 3.7.0 which hides the 3.8.1 provided by your Ansible community package installation.

If you simply delete the community.docker version you installed manually (in `/home/timocov/.ansible/collections/ansible_collections/community/docker`) it should no longer output this warning.

**Comment by timocov** [comment]
Ah sorry my bad. I relied on the output

```
ansible-galaxy install -r requirements.yml
Starting galaxy role install process
[WARNING]: - artis3n.tailscale (v4.4.1) is already installed - use --force to change version to unspecified
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.
```

and thought everything was up-to-date. Installing with `--force` flag installed latest versions of collections. Thanks!
