### ISSUE TITLE
Show global state (docker ps or docker-compose ps)

### ISSUE THREAD

**Issue by fredbcode** [ansible-collections/community.docker#862]
Maybe I missed something but I found no way to show all containers state ?

Something like: 

community.docker.docker_container_info:
  name: all 
  
 I'm just searching a way to see the containers state of my compose or at least for all the containers (with or without compose)

**Comment by felixfontein** [comment]
You can use the `community.docker.docker_host_info` module with `containers: true`, `containers_all: true`, and `verbose_output: true`. You can use `containers_filters` to filter for specific groups of containers.

For Docker Compose there's no specific module to show the running containers for a Compose.

**Comment by felixfontein** [comment]
Closing since this is resolved (I think).
