### ISSUE TITLE
bug with with requests affecting docker_login

### ISSUE THREAD

**Issue by bassam55** [ansible-collections/community.docker#866]
There is a bug with the new versions of `requests` Found [here](https://github.com/docker/docker-py/issues/3256).
I'm getting the error when I try to run the docker_login module
Does anyone know a temporary fix untill they patch it?

**Comment by felixfontein** [comment]
Please check out the latest release (community.docker 3.10.2). That should work both with requests 2.32.0/1, and 2.23.2 and later, at least for all modules that use the vendored Docker SDK for Python code. The Docker Swarm modules and the docker_compose v1 module use Docker SDK for Python, which currently has no fixed version.

(Also check out closed issues. There are already two for this problem. :) )

**Comment by bassam55** [comment]
Thank you. I just saw the fix.
