### ISSUE TITLE
docker_compose_v2 - pull fails with strange tls error

### ISSUE THREAD

**Issue by Hannes1909** [ansible-collections/community.docker#957]
##### SUMMARY

Docker Compose Pull sometimes fails with certificate error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```
community.docker.docker_compose_v2
```

##### ANSIBLE VERSION

```
ansible [core 2.16.5]
  config file = /home/hannes/Dokumente/dev/gitlab/Ansible/ansible.cfg
  configured module search path = ['/home/hannes/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /nix/store/a5k2lpbxj419kzn2pyz55gql35pbg8xx-python3.12-ansible-core-2.16.5/lib/python3.12/site-packages/ansible
  ansible collection location = /home/hannes/.ansible/collections:/usr/share/ansible/collections
  executable location = /nix/store/a5k2lpbxj419kzn2pyz55gql35pbg8xx-python3.12-ansible-core-2.16.5/bin/ansible
  python version = 3.12.4 (main, Jun  6 2024, 18:26:44) [GCC 13.3.0] (/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```
# /nix/store/kxx2qjjm9la1fl1wcj7pck9lpkmva810-python3.12-ansible-10.1.0/lib/python3.12/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 3.10.4 
```

##### CONFIGURATION

```
CONFIG_FILE() = /home/hannes/Dokumente/dev/gitlab/Ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/hannes/Dokumente/dev/gitlab/Ansible/ansible.cfg) = ['/home/hannes/Dokumente/dev/gitlab/Ansible>
DEFAULT_REMOTE_USER(/home/hannes/Dokumente/dev/gitlab/Ansible/ansible.cfg) = hannes
EDITOR(env: EDITOR) = nano
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

I run ansible from my workstation, NixOS unstable. The target is a Ubuntu 24.04 server, running as VM on PVE.

##### STEPS TO REPRODUCE

Sometimes the Ansible triggered docker compose pull reports errors like below, subsequent runs work flawlessly again. Running `docker compose pull` manually on the target host has never thrown an error like this.
I am using Traefik:Latest Container as Reverse-Proxy in my Setup, handling SSL with LetsEncrypt DNS Plugin, since this might be relevant to the error below.

When running the same playbook, same settings, same hosts again after the error, it usually succeeds, sometimes I had to call it three or four times in a row.

The failing task in my playbook is pretty straightforward:

```yaml
  tasks:
    - name: Docker Compose pull
      community.docker.docker_compose_v2:
        project_src: /srv/docker
        pull: always
        remove_orphans: true
      notify: Docker Compose Restart
```

##### EXPECTED RESULTS

The Task Docker Compose pull should return OK (if no new images are available) or CHANGED (if one or more images got updated) for the host in my inventory [docker]:
```
TASK [Docker Compose pull] 
*************************************************
ok: [docker]
```
```
TASK [Docker Compose pull] 
*************************************************
changed: [docker]
```
##### ACTUAL RESULTS

The compose pull fails, stating the (SSL?) context aborted due to a invalid certificate.

```paste below
fatal: [docker]: FAILED! => [... Infos about running container, config, etc ...]

"msg": "Error when processing vaultwarden: Head \"https://registry-1.docker.io/v2/vaultwarden/server/manifests/latest\": Get \"https://auth.docker.io/token?scope=repository%3Avaultwarden%2Fserver%3Apull&service=registry.docker.io\": tls: failed to verify certificate: x509: certificate is valid for 24e615d1eaf1b77cf233b984e863d481.0fc2ad1710547162e5d9867c310771e7.traefik.default, not auth.docker.io
            Error when processing netbox_redis: context canceled
            [... my other containers in the compose file are listed here inbetween, redacted for readability ...]
            Error response from daemon: Head \"https://registry-1.docker.io/v2/vaultwarden/server/manifests/latest\": 
            Get \"https://auth.docker.io/token?scope=repository%3Avaultwarden%2Fserver%3Apull&service=registry.docker.io\": 
            tls: failed to verify certificate: x509: certificate is valid for 24e615d1eaf1b77cf233b984e863d481.0fc2ad1710547162e5d9867c310771e7.traefik.default, not auth.docker.io", 
```
The same error is replicated in the `stderr`-section of the log. The hashes displayed in the hostname the certificate should belong to do not seem to be any hashes from my running containers (compared with every hash in docker inspect), so I'm also a little lost here WHAT certificate exactly is presented to docker compose in the first place. The hashes seem to change though - maybe after sucessfull updates of the containers, I cant tell for sure.

Traefik Configuration is also pretty straightforward - it binds to Ports 80 and 443, presents a certificateresolver with Hetzner DNS plugin since my containers run in a local environment and cannot be reached from public internet for HTTPS-challange.

**Comment by felixfontein** [comment]
The module doesn't do anything else than running `docker compose up --pull=always`, and that seems to produce the error. So this is a problem with your target.

You could try to figure out the exact command line it runs, and try to run that one in exactly the same environment (user etc.) that Ansible uses to execute the module. Maybe then you can reproduce it when running that manually.

**Comment by Hannes1909** [comment]
Thanks for the hint, im gonna try the exact command from ansible next time it fails - as far as i can remember the commandline is also in the fatal-errormessage. Thats what i thought, too, about the module - the commandline from Ansible is slightly longer than my manual cd && docker compose pull. 

I'll keep an eye on it and update here when I have reproduced the issue (be it ansible-related or not :) ). If you want, we can close the issue for now, so it doesnt spam the queue. I can reopen it later or just add the information related to the error when I find another root-cause.

**Comment by Hannes1909** [comment]
The command run by ansible is:
`/usr/bin/docker compose --ansi never --progress plain --project-directory /srv/docker up --detach --no-color --quiet-pull --pull always --remove-orphans --`
I wonder where the last two hyphens are from, but the same command pulls the containers successfully, when run manually via ssh (even with the two hyphens at the end). I don't think thats an ansible related issue though, so I'm closing the issue.

**Comment by felixfontein** [comment]
`--` usually says "from here on, all parameters are positional parameters", so that if you want to rename a file called `-r` to `-f`, you do `mv -- -r -f`. Without `--`, `mv` would interpret `-r` and `-f` as flags. (The positional parameters for the Compose command would be services to use, if you use the `services` option of the module.)

My guess is that in your case the environments are slightly different. Did you run `ssh target /usr/bin/docker compose --ansi never --progress plain --project-directory /srv/docker up --detach --no-color --quiet-pull --pull always --remove-orphans --`? Or did you run `ssh target` and then run `/usr/bin/docker compose --ansi never --progress plain --project-directory /srv/docker up --detach --no-color --quiet-pull --pull always --remove-orphans --`? Those two behave quite different, as you can see with `ssh target env` vs. `ssh target` and then `env`. For one of my servers, for example, `$PATH` differs in these two situations, `$LANG` and `$TERM` are only set in one case (`ssh target` and then `env`), and some other smaller differences.

**Comment by Hannes1909** [comment]
Indeed i ssh'd to the target and ran the command locally - im gonna try the whole commandline via ssh :) Thanks for all the information and support!

PS: I can confirm the differences in `env` (as an example for one of my machines also). Could be right, different execution based on the "environment" (not only `env`, but other parameters too, maybe). Im gonna test and report back.

**Comment by Hannes1909** [comment]
i believe it has been a DNS issue - my lazy a** configured a catchall-domain so i didn't have to manually configure hostnames for my docker containers but had every "unknown" hostname pointing to the docker host instead. this was convenient but since i added my dns configuration in my ansible playbook, i can manage it as code and dont need the *.my.local redirect anymore.

I think the issue happened, when docker compose pull (or any other https-based call) recieved the url as dns-answer with the local search domain and got redirected to the docker host (running traefik, therefore the strange certificate names). I still cant wrap my head around this issue completely, since the HTTPS calls have a valid and complete URL, not only hostnames where it would make sense for DNS to add my local domain.

Right now I'm still testing without the *.my.local catchall-rule in my DNS, but i could not reproduce the issue since. Sorry for causing such a ruckus here :)

**Comment by felixfontein** [comment]
Well, I'm glad you figured it out :) I guess this is another case where too much magic comes back to bite you ;)
