### ISSUE TITLE
docker_container_info  module always returns container:none even if the container exists

### ISSUE THREAD

**Issue by stefano-cherchi** [ansible-collections/community.docker#959]
##### SUMMARY
The module `community.docker.docker_container_info` always returns `container: none, exists: false` even if a container with the specified name is up and running on the host

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.docker.docker_container_info

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.12]
```

##### COLLECTION VERSION

```paste below
# /home/debian/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.12.1

# /home/debian/ansible_venv/lib/python3.9/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 3.4.11
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/debian/myproject/ansible.cfg
DEFAULT_NO_TARGET_SYSLOG(/home/debian/myproject/ansible.cfg) = True
DEFAULT_TIMEOUT(/home/debian/myproject/ansible.cfg) = 120
HOST_KEY_CHECKING(/home/debian/myproject/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Both the Ansible machine and the target hosts run a freshly installed Debian 11.10, Python 3.9.2

##### STEPS TO REPRODUCE

Write an ansible playbook that runs the following tasks:
* Check the status of a docker container using the module community.docker.docker_container_info (e.g: nginx)
* Print the results using the module ansible.builtin.debug

```yaml
- name: Check if the Nginx service already exists
 community.docker.docker_container_info:
   name: nginx
 register: nginx_container

- name: DEBUG - Print the nginx_container
 ansible.builtin.debug:
   msg: "{{ nginx_container }}"
```

##### EXPECTED RESULTS

The output should show the info of the running nginx container

##### ACTUAL RESULTS

The output is always as follows, even if the container is running 

```paste below
 TASK [nginx : Check if the Nginx service already exists] ***************************************************************************************************************
task path: /home/debian/myproject/roles/nginx/tasks/main.yml:323
ok: [layer1] => {
    "changed": false,
    "container": null,
    "exists": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "ca_path": null,
            "client_cert": null,
            "client_key": null,
            "debug": false,
            "docker_host": "unix:///var/run/docker.sock",
            "name": "nginx",
            "ssl_version": null,
            "timeout": 60,
            "tls": false,
            "tls_hostname": null,
            "use_ssh_client": false,
            "validate_certs": false
        }
    }
}

TASK [nginx : DEBUG - Print the nginx_container] ***********************************************************************************************************************
task path: /home/debian/myproject/roles/nginx/tasks/main.yml:328
ok: [layer1] => {
    "msg": {
        "changed": false,
        "container": null,
        "exists": false,
        "failed": false
    }
}
```

The container is currently running on the host:
<img width="762" alt="Screenshot 2024-08-27 at 9 56 33 AM" src="https://github.com/user-attachments/assets/f7a182a9-a7fd-4fdd-8ea9-653dfd2ca8db">
<img width="762" alt="Screenshot 2024-08-27 at 9 53 35 AM" src="https://github.com/user-attachments/assets/26895dc6-801f-458f-9fba-1122a1e25a92">

**Comment by felixfontein** [comment]
Since the module works fine for me, can you check a few things:
1. Are you running the module with the same Docker Daemon than the CLI `docker container inspect` command? I.e. is the module actually running on the right machine, and does `docker -H unix:///var/run/docker.sock container inspect nginx` on that machine gives the same results?
2. Can you add a `command: docker -H unix:///var/run/docker.sock container inspect nginx` task to the playbook?

In case this doesn't help, what is the Docker version running on the target?

**Comment by stefano-cherchi** [comment]
Hi @felixfontein , thanks for your quick reply. I added the `command:` task that you suggested and it turned out that, in fact, the container was removed by a previous `include_role` that isn't properly logging the task. I'm closing the issue. Sorry for the inconvenience.

**Comment by felixfontein** [comment]
No worries, I'm glad it turned out to be that simple! :)
