### ISSUE TITLE
Fail to install the collection with ansible core 2.11.12 (install by molecule)

### ISSUE THREAD

**Issue by xtero** [ansible-collections/community.docker#972]
##### SUMMARY

While I'm trying to run a molecule scenario with docker driver to test my role, molecule download the collection with the following command:
`ansible-galaxy collection install -vvv community.docker:>=3.0.2`
You can consult the stack trace here from molecule : https://gist.github.com/xtero/d57f7971302720b96d5678bc4398ae8d
And a second one while I'm running it manually in a more verbose way : https://gist.github.com/xtero/1664b118afe568091d69d15e1ad392fa

I have gitlab pipeline that are running very similar scenario with ansible core from 2.12 up to 2.17. And everything is fine with them.
I only have the issue with ansible core 2.11. 
In addition, if I run the install with --no-cache option, the installation is working fine. But I don't understand why as the running context is fresh (docker context). And of course, as it's called by molecule, I can't add the --no-cache option.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Installation of the collection

##### ANSIBLE VERSION

```
$ ansible --version
ansible [core 2.11.12]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /venv/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /venv/bin/ansible
  python version = 3.10.15 (main, Sep 11 2024, 09:20:18) [GCC 12.2.1 20220924]
  jinja version = 3.1.4
  libyaml = True
$ molecule --version
molecule 4.0.4 using python 3.10
    ansible:2.11.12
    azure:23.0.0 from molecule_plugins
    containers:23.0.0 from molecule_plugins requiring collections: ansible.posix>=1.3.0 community.docker>=1.9.1 containers.podman>=1.8.1
    delegated:4.0.4 from molecule
    docker:23.0.0 from molecule_plugins requiring collections: community.docker>=3.0.2 ansible.posix>=1.4.0
    ec2:23.0.0 from molecule_plugins
    gce:23.0.0 from molecule_plugins requiring collections: google.cloud>=1.0.2 community.crypto>=1.8.0
    podman:23.0.0 from molecule_plugins requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:23.0.0 from molecule_plugins
```

##### COLLECTION VERSION

N/A

##### CONFIGURATION

```
$ ansible-config dump --only-changed

```
No changes

##### OS / ENVIRONMENT

Running in docker image docker:20.10.23-dind with following added packages :
```
bash-5.2.15-r0 x86_64
ca-certificates-20220614-r4 x86_64
ca-certificates-bundle-20220614-r4 x86_64
curl-8.5.0-r0 x86_64
libcurl-8.5.0-r0 x86_64
file-5.43-r0 x86_64
libmagic-5.43-r0 x86_64
libgcc-12.2.1_git20220924-r4 x86_64
libstdc++-12.2.1_git20220924-r4 x86_64
git-2.38.5-r0 x86_64
libgcc-12.2.1_git20220924-r4 x86_64
libstdc++-12.2.1_git20220924-r4 x86_64
jq-1.6-r2 x86_64
openssh-client-common-9.1_p1-r2 x86_64
openssh-client-default-9.1_p1-r2 x86_64
python3-3.10.14-r1 x86_64
py3-pip-22.3.1-r1 x86_64
rsync-3.2.7-r0 x86_64
```
And the following python libraries added with pip :
``` 
ansible                   4.10.0
ansible-compat            2.2.7
ansible-core              2.11.12
ansible-lint              5.4.0
flake8                    6.0.0
flake8-markdown           0.4.0
hvac                      1.1.0
jinjaninja                0.1.2
jmespath                  1.0.1
molecule                  4.0.4
molecule-plugins          23.0.0
netaddr                   0.8.0
openshift                 0.13.1
openstacksdk              0.61.0
paramiko                  3.2.0
pbr                       6.0.0
pydocstyle                6.3.0
pylint                    2.17.4
pytest                    8.2.2
pytest-molecule           2.0.0
requests                  2.31.0
setuptools                70.0.0
six                       1.16.0
wheel                     0.43.0
yamllint                  1.32.0
```

##### STEPS TO REPRODUCE

with the context described above, just try to install the collection with the following command :
```
$ ansible-galaxy collection install 'community.docker:>=3.0.2'
```

##### EXPECTED RESULTS

The collection should be installed

##### ACTUAL RESULTS

The collection is failing to install

**Comment by felixfontein** [comment]
This is a problem with ansible-core and Ansible Galaxy, not with this collection. You wlil also not be able to install any other collection from Galaxy.

Please note that ansible-core 2.11 is End of Life ([and has been for over two years](https://docs.ansible.com/ansible-core/devel/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix)) and no longer works with Ansible Galaxy (see for example https://forum.ansible.com/t/1281/6 and below).
