### ISSUE TITLE
Constructed inventories need to end in "docker.yaml" or "docker.yml"

### ISSUE THREAD

**Issue by miquelmassot** [ansible-collections/community.docker#973]
##### SUMMARY

Constructed inventories will not pass a verification check unless their filename ends with `docker.yaml` or `docker.yml`, as enforced in https://github.com/ansible-collections/community.docker/blob/main/plugins/inventory/docker_containers.py#L367. 

Please document this requirement or remove it - as it is not covered in https://docs.ansible.com/ansible/latest/collections/community/docker/docker_containers_inventory.html 
##### ISSUE TYPE
- Bug Report

**Comment by felixfontein** [comment]
Check out this line: https://github.com/ansible-collections/community.docker/blob/main/plugins/inventory/docker_containers.py#L28

Or alternatively in the documentation you linked to: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_containers_inventory.html#synopsis
