### ISSUE TITLE
Feature Request: Exec functionality for docker_compose module

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/community.docker#98]
Currently, I do not see a way to interrace with containers leveraging the exec command.  It would be great if this was natively supported by this docker collection.

**Comment by felixfontein** [comment]
@ryanmerolle the connection plugins ([community.docker.docker](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_connection.html#ansible-collections-community-docker-docker-connection) and [community.docker.docker_api](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_api_connection.html#ansible-collections-community-docker-docker-api-connection)) both allow to run commands in Docker containers via exec.

I guess you're interested in something like the [ansible.builtin.command](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html#ansible-collections-ansible-builtin-command-module) module for Docker containers?

**Comment by ryanmerolle** [comment]
I was using this with a gitlab runner and did not have a collection built into my ansible container.  I can just bake the collection into my container.  I was totally not even thinking about the community docker collection, but ha I raised my request in said repo.  I am happy to close this honestly.

**Comment by felixfontein** [comment]
@ryanmerolle I've created a PR for an exec module in #105, feel free to test it out (or review it)!

**Comment by ryanmerolle** [comment]
@felixfontein I apologize for forgetting about this.  The module works perfectly for my needs and is much appreciated.  Would it be challenging to also extend to docker-compose exec?  That would allow me to get rid of the last of my ansible.builtin.shell modules for docker-compose exec.

Again I appreciate the PR you provided.  Thanks!

**Comment by felixfontein** [comment]
> @felixfontein I apologize for forgetting about this. The module works perfectly for my needs and is much appreciated.

Thanks!

> Would it be challenging to also extend to docker-compose exec?

I think so, but I'm not sure. docker-compose is a separate (Python) program on top of Docker itself, so there's no way to control it with with Docker daemon. The docker_compose module basically hooks into docker-compose (since it's Python) and makes it do the things it wants. I guess that emulating `docker-compose exec` will require a similar approach to find out the actual container ID. In any case, I'm not very familiar with docker-compose (I also don't use it), maybe it's simpler to do...

**Comment by felixfontein** [comment]
I reopened this and adjusted the title, maybe someone else is interested in working on this :)

**Comment by felixfontein** [comment]
As written above, the hard part here is figuring out the correct container ID. Everything else can be done as in the docker_container_exec module (I guess we can move some more stuff from it into module_utils to reduce duplicate code).

**Comment by Ajpantuso** [comment]
Yeah, it seems like initializing a compose project and  inserting [this](https://github.com/docker/compose/blob/4a51af09d6cdb9407a6717334333900327bc9302/compose/cli/main.py#L561-L562), [this](https://github.com/docker/compose/blob/4a51af09d6cdb9407a6717334333900327bc9302/compose/cli/main.py#L573-L575), and [this](https://github.com/docker/compose/blob/4a51af09d6cdb9407a6717334333900327bc9302/compose/cli/main.py#L597) from `docker-compose` into this [section](https://github.com/ansible-collections/community.docker/blob/4dfc3ae5d734d85a91e4d36d96fc95b23c526425/plugins/modules/docker_container_exec.py#L193-L202) of the `docker_contatiner_exec` module will transform it into a `docker_compose_exec` module.

**Comment by crunchyericford** [comment]
Any movement on this, would love to have this functionality

**Comment by felixfontein** [comment]
The community.docker.docker_compose module has been removed from today's 4.0.0 release. If you are still using it, please upgrade to community.docker.docker_compose_v2, which no longer uses the End of Life versions Docker Compose 1.x.y, but Docker's Compose plugin (version 2.x.y range).

For community.docker.docker_compose_v2, you can use community.docker.docker_compose_v2_run or community.docker.docker_compose_v2_exec.
